version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
        - "8042:80"
    volumes:
      - ./scd-id:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    extra_hosts:
      - "host.docker.internal:host-gateway"
  php:
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./php:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  go:
    build:
      context: .
      dockerfile: ./go/Dockerfile
    volumes:
      - ./go:/app/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8045:5000"