version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
        - "8042:80"
    volumes:
      - ./php:/var/www/html
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx/
    depends_on:
      - php
    extra_hosts:
      - "host.docker.internal:host-gateway"
  php:
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./php:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  go:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./go/Dockerfile
    volumes:
      - ./go:/app/
      - ./php:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8045:5000"
  
  # cron:
  #   build:
  #     context: .
  #     dockerfile: ./cron/Dockerfile
  #   volumes:
  #     - ./go:/app/
  #     - ./cron:/home/
  #   depends_on:
  #     - go
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"