// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNamePetunjukSoalEng = "petunjuk_soal_eng"

// PetunjukSoalEng mapped from table <petunjuk_soal_eng>
type PetunjukSoalEng struct {
	IDPetunjuk  int32  `gorm:"column:id_petunjuk;primaryKey;autoIncrement:true" json:"id_petunjuk"`
	IsiPetunjuk string `gorm:"column:isi_petunjuk" json:"isi_petunjuk"`
	UUID        string `gorm:"column:uuid" json:"uuid"`
	Keterangan  string `gorm:"column:keterangan" json:"keterangan"`
}

// TableName PetunjukSoalEng's table name
func (*PetunjukSoalEng) TableName() string {
	return TableNamePetunjukSoalEng
}
