// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameQuizSesiDetil = "quiz_sesi_detil"

// QuizSesiDetil mapped from table <quiz_sesi_detil>
type QuizSesiDetil struct {
	IDQuizSesi   int32 `gorm:"column:id_quiz_sesi;primaryKey;autoIncrement:true" json:"id_quiz_sesi"`
	IDQuiz       int32 `gorm:"column:id_quiz" json:"id_quiz"`
	IDSesiMaster int32 `gorm:"column:id_sesi_master" json:"id_sesi_master"`
	Urutan       int32 `gorm:"column:urutan" json:"urutan"`
	Durasi       int32 `gorm:"column:durasi" json:"durasi"`
	KunciWaktu   int32 `gorm:"column:kunci_waktu" json:"kunci_waktu"`
}

// TableName QuizSesiDetil's table name
func (*QuizSesiDetil) TableName() string {
	return TableNameQuizSesiDetil
}
