// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameQuizSesiTemplateLampiran = "quiz_sesi_template_lampiran"

// QuizSesiTemplateLampiran mapped from table <quiz_sesi_template_lampiran>
type QuizSesiTemplateLampiran struct {
	IDQuizTemplate int64 `gorm:"column:id_quiz_template;primaryKey" json:"id_quiz_template"`
	IDReport       int64 `gorm:"column:id_report;primaryKey" json:"id_report"`
}

// TableName QuizSesiTemplateLampiran's table name
func (*QuizSesiTemplateLampiran) TableName() string {
	return TableNameQuizSesiTemplateLampiran
}
