// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameQuizSesiTemplate = "quiz_sesi_template"

// QuizSesiTemplate mapped from table <quiz_sesi_template>
type QuizSesiTemplate struct {
	IDQuizTemplate int32  `gorm:"column:id_quiz_template;primaryKey;autoIncrement:true" json:"id_quiz_template"`
	NamaSesi       string `gorm:"column:nama_sesi" json:"nama_sesi"`
	Gambar         string `gorm:"column:gambar" json:"gambar"`
	SkoringTabel   string `gorm:"column:skoring_tabel" json:"skoring_tabel"`
	UUID           string `gorm:"column:uuid" json:"uuid"`
	Jenis          string `gorm:"column:jenis;comment:demo atao quiz" json:"jenis"` // demo atao quiz
	Kode           string `gorm:"column:kode" json:"kode"`
}

// TableName QuizSesiTemplate's table name
func (*QuizSesiTemplate) TableName() string {
	return TableNameQuizSesiTemplate
}
