// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameQuizSesiMappingSmk = "quiz_sesi_mapping_smk"

// QuizSesiMappingSmk mapped from table <quiz_sesi_mapping_smk>
type QuizSesiMappingSmk struct {
	IDQuizMapping int32  `gorm:"column:id_quiz_mapping;primaryKey;autoIncrement:true" json:"id_quiz_mapping"`
	IDQuiz        int32  `gorm:"column:id_quiz" json:"id_quiz"`
	IDKegiatan    int32  `gorm:"column:id_kegiatan;comment:ke Tabel Soal Peminatan SMK" json:"id_kegiatan"` // ke Tabel Soal Peminatan SMK
	UUID          string `gorm:"column:uuid" json:"uuid"`
}

// TableName QuizSesiMappingSmk's table name
func (*QuizSesiMappingSmk) TableName() string {
	return TableNameQuizSesiMappingSmk
}
