// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameQuizSesiTemplateReport = "quiz_sesi_template_report"

// QuizSesiTemplateReport mapped from table <quiz_sesi_template_report>
type QuizSesiTemplateReport struct {
	IDQuizReportTemplate int32  `gorm:"column:id_quiz_report_template;primaryKey;autoIncrement:true" json:"id_quiz_report_template"`
	IDQuizTemplate       int32  `gorm:"column:id_quiz_template" json:"id_quiz_template"`
	Urutan               int32  `gorm:"column:urutan" json:"urutan"`
	IDReport             int32  `gorm:"column:id_report" json:"id_report"`
	UUID                 string `gorm:"column:uuid" json:"uuid"`
}

// TableName QuizSesiTemplateReport's table name
func (*QuizSesiTemplateReport) TableName() string {
	return TableNameQuizSesiTemplateReport
}
