// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameRefKlasifikasiMinatMan = "ref_klasifikasi_minat_man"

// RefKlasifikasiMinatMan mapped from table <ref_klasifikasi_minat_man>
type RefKlasifikasiMinatMan struct {
	ID          int32  `gorm:"column:id;primaryKey" json:"id"`
	Skor        int32  `gorm:"column:skor;not null" json:"skor"`
	Klasifikasi string `gorm:"column:klasifikasi;not null" json:"klasifikasi"`
}

// TableName RefKlasifikasiMinatMan's table name
func (*RefKlasifikasiMinatMan) TableName() string {
	return TableNameRefKlasifikasiMinatMan
}
