// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameRefRekomendasiMinatMan = "ref_rekomendasi_minat_man"

// RefRekomendasiMinatMan mapped from table <ref_rekomendasi_minat_man>
type RefRekomendasiMinatMan struct {
	ID          int32  `gorm:"column:id;primaryKey" json:"id"`
	IlmuAlam    int32  `gorm:"column:ilmu_alam" json:"ilmu_alam"`
	IlmuSosial  int32  `gorm:"column:ilmu_sosial" json:"ilmu_sosial"`
	Perbedaan   int32  `gorm:"column:perbedaan" json:"perbedaan"`
	Rekomendasi string `gorm:"column:rekomendasi" json:"rekomendasi"`
}

// TableName RefRekomendasiMinatMan's table name
func (*RefRekomendasiMinatMan) TableName() string {
	return TableNameRefRekomendasiMinatMan
}
