// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameRefKomponenGayaPekerjaan = "ref_komponen_gaya_pekerjaan"

// RefKomponenGayaPekerjaan mapped from table <ref_komponen_gaya_pekerjaan>
type RefKomponenGayaPekerjaan struct {
	NamaKomponen  string `gorm:"column:nama_komponen" json:"nama_komponen"`
	Kode          string `gorm:"column:kode" json:"kode"`
	No            string `gorm:"column:no;primaryKey" json:"no"`
	CetakKomponen string `gorm:"column:cetak_komponen" json:"cetak_komponen"`
	Deskripsi     string `gorm:"column:deskripsi" json:"deskripsi"`
	Pekerjaan     string `gorm:"column:pekerjaan" json:"pekerjaan"`
	Gambar        string `gorm:"column:gambar" json:"gambar"`
}

// TableName RefKomponenGayaPekerjaan's table name
func (*RefKomponenGayaPekerjaan) TableName() string {
	return TableNameRefKomponenGayaPekerjaan
}
