// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameRefRangkingTmi = "ref_rangking_tmi"

// RefRangkingTmi mapped from table <ref_rangking_tmi>
type RefRangkingTmi struct {
	ID       int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Rangking int32 `gorm:"column:rangking;not null" json:"rangking"`
	Skor     int32 `gorm:"column:skor;not null" json:"skor"`
}

// TableName RefRangkingTmi's table name
func (*RefRangkingTmi) TableName() string {
	return TableNameRefRangkingTmi
}
