// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameRefRekomendasiAkhirSma = "ref_rekomendasi_akhir_sma"

// RefRekomendasiAkhirSma mapped from table <ref_rekomendasi_akhir_sma>
type RefRekomendasiAkhirSma struct {
	ID                  int32  `gorm:"column:id;primaryKey" json:"id"`
	RekomMinat          string `gorm:"column:rekom_minat" json:"rekom_minat"`
	RekomSikapPelajaran string `gorm:"column:rekom_sikap_pelajaran" json:"rekom_sikap_pelajaran"`
	RekomTmi            string `gorm:"column:rekom_tmi" json:"rekom_tmi"`
	RekomAkhir          string `gorm:"column:rekom_akhir" json:"rekom_akhir"`
}

// TableName RefRekomendasiAkhirSma's table name
func (*RefRekomendasiAkhirSma) TableName() string {
	return TableNameRefRekomendasiAkhirSma
}
