// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameRefSkoringWlb = "ref_skoring_wlb"

// RefSkoringWlb mapped from table <ref_skoring_wlb>
type RefSkoringWlb struct {
	Skor  int16 `gorm:"column:skor;primaryKey" json:"skor"`
	Nilai int16 `gorm:"column:nilai" json:"nilai"`
}

// TableName RefSkoringWlb's table name
func (*RefSkoringWlb) TableName() string {
	return TableNameRefSkoringWlb
}
