// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameSkorKuliahSosial = "skor_kuliah_sosial"

// SkorKuliahSosial mapped from table <skor_kuliah_sosial>
type SkorKuliahSosial struct {
	IDUser    int32 `gorm:"column:id_user;primaryKey" json:"id_user"`
	IDQuiz    int32 `gorm:"column:id_quiz;primaryKey" json:"id_quiz"`
	MinatIps1 int32 `gorm:"column:minat_ips1" json:"minat_ips1"`
	MinatIps2 int32 `gorm:"column:minat_ips2" json:"minat_ips2"`
	MinatIps3 int32 `gorm:"column:minat_ips3" json:"minat_ips3"`
	MinatIps4 int32 `gorm:"column:minat_ips4" json:"minat_ips4"`
	MinatIps5 int32 `gorm:"column:minat_ips5" json:"minat_ips5"`
}

// TableName SkorKuliahSosial's table name
func (*SkorKuliahSosial) TableName() string {
	return TableNameSkorKuliahSosial
}
