// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameSkorKuliahAlam = "skor_kuliah_alam"

// SkorKuliahAlam mapped from table <skor_kuliah_alam>
type SkorKuliahAlam struct {
	IDUser    int32 `gorm:"column:id_user;primaryKey" json:"id_user"`
	IDQuiz    int32 `gorm:"column:id_quiz;primaryKey" json:"id_quiz"`
	MinatIpa1 int32 `gorm:"column:minat_ipa1" json:"minat_ipa1"`
	MinatIpa2 int32 `gorm:"column:minat_ipa2" json:"minat_ipa2"`
	MinatIpa3 int32 `gorm:"column:minat_ipa3" json:"minat_ipa3"`
	MinatIpa4 int32 `gorm:"column:minat_ipa4" json:"minat_ipa4"`
	MinatIpa5 int32 `gorm:"column:minat_ipa5" json:"minat_ipa5"`
}

// TableName SkorKuliahAlam's table name
func (*SkorKuliahAlam) TableName() string {
	return TableNameSkorKuliahAlam
}
