// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameSkorPeminatanSmk = "skor_peminatan_smk"

// SkorPeminatanSmk mapped from table <skor_peminatan_smk>
type SkorPeminatanSmk struct {
	IDUser  int32  `gorm:"column:id_user;primaryKey" json:"id_user"`
	IDQuiz  int32  `gorm:"column:id_quiz;primaryKey" json:"id_quiz"`
	Minat1  string `gorm:"column:minat_1" json:"minat_1"`
	Minat2  string `gorm:"column:minat_2" json:"minat_2"`
	Minat3  string `gorm:"column:minat_3" json:"minat_3"`
	Minat4  string `gorm:"column:minat_4" json:"minat_4"`
	Minat5  string `gorm:"column:minat_5" json:"minat_5"`
	Minat6  string `gorm:"column:minat_6" json:"minat_6"`
	Minat7  string `gorm:"column:minat_7" json:"minat_7"`
	Minat8  string `gorm:"column:minat_8" json:"minat_8"`
	Minat9  string `gorm:"column:minat_9" json:"minat_9"`
	Minat10 string `gorm:"column:minat_10" json:"minat_10"`
	Minat11 string `gorm:"column:minat_11" json:"minat_11"`
	Minat12 string `gorm:"column:minat_12" json:"minat_12"`
	Minat13 string `gorm:"column:minat_13" json:"minat_13"`
	Minat14 string `gorm:"column:minat_14" json:"minat_14"`
	Minat15 string `gorm:"column:minat_15" json:"minat_15"`
}

// TableName SkorPeminatanSmk's table name
func (*SkorPeminatanSmk) TableName() string {
	return TableNameSkorPeminatanSmk
}
