// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameSkoringMinatLengkap = "skoring_minat_lengkap"

// SkoringMinatLengkap mapped from table <skoring_minat_lengkap>
type SkoringMinatLengkap struct {
	ID                  int32   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	IDUser              int32   `gorm:"column:id_user" json:"id_user"`
	IDQuiz              int32   `gorm:"column:id_quiz" json:"id_quiz"`
	TpaIu               int32   `gorm:"column:tpa_iu" json:"tpa_iu"`
	TpaPv               int32   `gorm:"column:tpa_pv" json:"tpa_pv"`
	TpaPk               int32   `gorm:"column:tpa_pk" json:"tpa_pk"`
	TpaPa               int32   `gorm:"column:tpa_pa" json:"tpa_pa"`
	TpaPs               int32   `gorm:"column:tpa_ps" json:"tpa_ps"`
	TpaPm               int32   `gorm:"column:tpa_pm" json:"tpa_pm"`
	TpaKt               int32   `gorm:"column:tpa_kt" json:"tpa_kt"`
	TpaIq               int32   `gorm:"column:tpa_iq" json:"tpa_iq"`
	SkorIq              float32 `gorm:"column:skor_iq" json:"skor_iq"`
	MinatIpa1           int32   `gorm:"column:minat_ipa1" json:"minat_ipa1"`
	MinatIpa2           int32   `gorm:"column:minat_ipa2" json:"minat_ipa2"`
	MinatIpa3           int32   `gorm:"column:minat_ipa3" json:"minat_ipa3"`
	MinatIpa4           int32   `gorm:"column:minat_ipa4" json:"minat_ipa4"`
	SikapAgm            int32   `gorm:"column:sikap_agm" json:"sikap_agm"`
	SikapPkn            int32   `gorm:"column:sikap_pkn" json:"sikap_pkn"`
	SikapInd            int32   `gorm:"column:sikap_ind" json:"sikap_ind"`
	SikapEng            int32   `gorm:"column:sikap_eng" json:"sikap_eng"`
	SikapMat            int32   `gorm:"column:sikap_mat" json:"sikap_mat"`
	SikapFis            int32   `gorm:"column:sikap_fis" json:"sikap_fis"`
	SikapBio            int32   `gorm:"column:sikap_bio" json:"sikap_bio"`
	SikapEko            int32   `gorm:"column:sikap_eko" json:"sikap_eko"`
	SikapSej            int32   `gorm:"column:sikap_sej" json:"sikap_sej"`
	SikapGeo            int32   `gorm:"column:sikap_geo" json:"sikap_geo"`
	TipojungE           int32   `gorm:"column:tipojung_e" json:"tipojung_e"`
	TipojungI           int32   `gorm:"column:tipojung_i" json:"tipojung_i"`
	TipojungS           int32   `gorm:"column:tipojung_s" json:"tipojung_s"`
	TipojungN           int32   `gorm:"column:tipojung_n" json:"tipojung_n"`
	TipojungT           int32   `gorm:"column:tipojung_t" json:"tipojung_t"`
	TipojungF           int32   `gorm:"column:tipojung_f" json:"tipojung_f"`
	TipojungJ           int32   `gorm:"column:tipojung_j" json:"tipojung_j"`
	TipojungP           int32   `gorm:"column:tipojung_p" json:"tipojung_p"`
	TipojungKode        string  `gorm:"column:tipojung_kode" json:"tipojung_kode"`
	PribadiMotivasi     int32   `gorm:"column:pribadi_motivasi" json:"pribadi_motivasi"`
	PribadiJuang        int32   `gorm:"column:pribadi_juang" json:"pribadi_juang"`
	PribadiYakin        int32   `gorm:"column:pribadi_yakin" json:"pribadi_yakin"`
	PribadiPercaya      int32   `gorm:"column:pribadi_percaya" json:"pribadi_percaya"`
	PribadiKonsep       int32   `gorm:"column:pribadi_konsep" json:"pribadi_konsep"`
	PribadiKreativitas  int32   `gorm:"column:pribadi_kreativitas" json:"pribadi_kreativitas"`
	PribadiMimpin       int32   `gorm:"column:pribadi_mimpin" json:"pribadi_mimpin"`
	PribadiEntrepreneur int32   `gorm:"column:pribadi_entrepreneur" json:"pribadi_entrepreneur"`
	PribadiStress       int32   `gorm:"column:pribadi_stress" json:"pribadi_stress"`
	PribadiEmosi        int32   `gorm:"column:pribadi_emosi" json:"pribadi_emosi"`
	PribadiSosial       int32   `gorm:"column:pribadi_sosial" json:"pribadi_sosial"`
	PribadiEmpati       int32   `gorm:"column:pribadi_empati" json:"pribadi_empati"`
	SelesaiSkoring      int32   `gorm:"column:selesai_skoring" json:"selesai_skoring"`
	MinatIpa5           int16   `gorm:"column:minat_ipa5" json:"minat_ipa5"`
	MinatIps1           int16   `gorm:"column:minat_ips1;primaryKey" json:"minat_ips1"`
	MinatIps2           int16   `gorm:"column:minat_ips2" json:"minat_ips2"`
	MinatIps3           int16   `gorm:"column:minat_ips3" json:"minat_ips3"`
	MinatIps4           int16   `gorm:"column:minat_ips4" json:"minat_ips4"`
	MinatIps5           int16   `gorm:"column:minat_ips5" json:"minat_ips5"`
	MinatDinas1         string  `gorm:"column:minat_dinas1;default:NULL" json:"minat_dinas1"`
	MinatDinas2         string  `gorm:"column:minat_dinas2;default:NULL" json:"minat_dinas2"`
	MinatDinas3         string  `gorm:"column:minat_dinas3;default:NULL" json:"minat_dinas3"`
	SuasanaKerja1       string  `gorm:"column:suasana_kerja1;default:0" json:"suasana_kerja1"`
	SuasanaKerja2       string  `gorm:"column:suasana_kerja2;default:0" json:"suasana_kerja2"`
	SuasanaKerja3       string  `gorm:"column:suasana_kerja3;default:0" json:"suasana_kerja3"`
}

// TableName SkoringMinatLengkap's table name
func (*SkoringMinatLengkap) TableName() string {
	return TableNameSkoringMinatLengkap
}
