// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameSkorSikapPelajaran = "skor_sikap_pelajaran"

// SkorSikapPelajaran mapped from table <skor_sikap_pelajaran>
type SkorSikapPelajaran struct {
	IDUser              int32  `gorm:"column:id_user;primaryKey" json:"id_user"`
	IDQuiz              int32  `gorm:"column:id_quiz;primaryKey" json:"id_quiz"`
	SikapAgm            int32  `gorm:"column:sikap_agm" json:"sikap_agm"`
	SikapPkn            int32  `gorm:"column:sikap_pkn" json:"sikap_pkn"`
	SikapInd            int32  `gorm:"column:sikap_ind" json:"sikap_ind"`
	SikapEng            int32  `gorm:"column:sikap_eng" json:"sikap_eng"`
	SikapMat            int32  `gorm:"column:sikap_mat" json:"sikap_mat"`
	SikapFis            int32  `gorm:"column:sikap_fis" json:"sikap_fis"`
	SikapBio            int32  `gorm:"column:sikap_bio" json:"sikap_bio"`
	SikapEko            int32  `gorm:"column:sikap_eko" json:"sikap_eko"`
	SikapSej            int32  `gorm:"column:sikap_sej" json:"sikap_sej"`
	SikapGeo            int32  `gorm:"column:sikap_geo" json:"sikap_geo"`
	KlasifikasiAgm      string `gorm:"column:klasifikasi_agm" json:"klasifikasi_agm"`
	KlasifikasiPkn      string `gorm:"column:klasifikasi_pkn" json:"klasifikasi_pkn"`
	KlasifikasiInd      string `gorm:"column:klasifikasi_ind" json:"klasifikasi_ind"`
	KlasifikasiEng      string `gorm:"column:klasifikasi_eng" json:"klasifikasi_eng"`
	KlasifikasiMat      string `gorm:"column:klasifikasi_mat" json:"klasifikasi_mat"`
	KlasifikasiFis      string `gorm:"column:klasifikasi_fis" json:"klasifikasi_fis"`
	KlasifikasiBio      string `gorm:"column:klasifikasi_bio" json:"klasifikasi_bio"`
	KlasifikasiEko      string `gorm:"column:klasifikasi_eko" json:"klasifikasi_eko"`
	KlasifikasiSej      string `gorm:"column:klasifikasi_sej" json:"klasifikasi_sej"`
	KlasifikasiGeo      string `gorm:"column:klasifikasi_geo" json:"klasifikasi_geo"`
	SikapRentang        int32  `gorm:"column:sikap_rentang" json:"sikap_rentang"`
	SikapIlmuAlam       int32  `gorm:"column:sikap_ilmu_alam" json:"sikap_ilmu_alam"`
	SikapIlmuSosial     int32  `gorm:"column:sikap_ilmu_sosial" json:"sikap_ilmu_sosial"`
	RekomSikapPelajaran string `gorm:"column:rekom_sikap_pelajaran" json:"rekom_sikap_pelajaran"`
}

// TableName SkorSikapPelajaran's table name
func (*SkorSikapPelajaran) TableName() string {
	return TableNameSkorSikapPelajaran
}
