// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameSoalMinatKuliahSuasanaKerja = "soal_minat_kuliah_suasana_kerja"

// SoalMinatKuliahSuasanaKerja mapped from table <soal_minat_kuliah_suasana_kerja>
type SoalMinatKuliahSuasanaKerja struct {
	IDKegiatan int32  `gorm:"column:id_kegiatan;primaryKey;autoIncrement:true" json:"id_kegiatan"`
	Nomor      string `gorm:"column:nomor" json:"nomor"`
	Kegiatan   string `gorm:"column:kegiatan" json:"kegiatan"`
	Gambar     string `gorm:"column:gambar" json:"gambar"`
	Keterangan string `gorm:"column:keterangan" json:"keterangan"`
	Deskripsi  string `gorm:"column:deskripsi" json:"deskripsi"`
	UUID       string `gorm:"column:uuid" json:"uuid"`
}

// TableName SoalMinatKuliahSuasanaKerja's table name
func (*SoalMinatKuliahSuasanaKerja) TableName() string {
	return TableNameSoalMinatKuliahSuasanaKerja
}
