// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameSoalSikapPelajaran = "soal_sikap_pelajaran"

// SoalSikapPelajaran mapped from table <soal_sikap_pelajaran>
type SoalSikapPelajaran struct {
	IDSoal        int32  `gorm:"column:id_soal;primaryKey;autoIncrement:true" json:"id_soal"`
	Urutan        int32  `gorm:"column:urutan" json:"urutan"`
	Pelajaran     string `gorm:"column:pelajaran" json:"pelajaran"`
	Kode          string `gorm:"column:kode" json:"kode"`
	SikapNegatif1 string `gorm:"column:sikap_negatif1" json:"sikap_negatif1"`
	SikapPositif1 string `gorm:"column:sikap_positif1" json:"sikap_positif1"`
	SikapNegatif2 string `gorm:"column:sikap_negatif2" json:"sikap_negatif2"`
	SikapPositif2 string `gorm:"column:sikap_positif2" json:"sikap_positif2"`
	SikapNegatif3 string `gorm:"column:sikap_negatif3" json:"sikap_negatif3"`
	SikapPositif3 string `gorm:"column:sikap_positif3" json:"sikap_positif3"`
	Kelompok      string `gorm:"column:kelompok" json:"kelompok"`
	FieldSkoring  string `gorm:"column:field_skoring" json:"field_skoring"`
	UUID          string `gorm:"column:uuid" json:"uuid"`
}

// TableName SoalSikapPelajaran's table name
func (*SoalSikapPelajaran) TableName() string {
	return TableNameSoalSikapPelajaran
}
