// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameSoalPeminatanSmk = "soal_peminatan_smk"

// SoalPeminatanSmk mapped from table <soal_peminatan_smk>
type SoalPeminatanSmk struct {
	IDKegiatan int32  `gorm:"column:id_kegiatan;primaryKey;autoIncrement:true" json:"id_kegiatan"`
	Nomor      string `gorm:"column:nomor" json:"nomor"`
	Kegiatan   string `gorm:"column:kegiatan" json:"kegiatan"`
	Gambar     string `gorm:"column:gambar" json:"gambar"`
	Keterangan string `gorm:"column:keterangan" json:"keterangan"`
	Deskripsi  string `gorm:"column:deskripsi" json:"deskripsi"`
	UUID       string `gorm:"column:uuid" json:"uuid"`
	Paket      string `gorm:"column:paket" json:"paket"`
}

// TableName SoalPeminatanSmk's table name
func (*SoalPeminatanSmk) TableName() string {
	return TableNameSoalPeminatanSmk
}
