// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package export

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"irwanka/sicerdas/utils/gen-model/entity"
)

func newQuizSesiUserJawaban(db *gorm.DB, opts ...gen.DOOption) quizSesiUserJawaban {
	_quizSesiUserJawaban := quizSesiUserJawaban{}

	_quizSesiUserJawaban.quizSesiUserJawabanDo.UseDB(db, opts...)
	_quizSesiUserJawaban.quizSesiUserJawabanDo.UseModel(&entity.QuizSesiUserJawaban{})

	tableName := _quizSesiUserJawaban.quizSesiUserJawabanDo.TableName()
	_quizSesiUserJawaban.ALL = field.NewAsterisk(tableName)
	_quizSesiUserJawaban.IDJawabanPeserta = field.NewInt32(tableName, "id_jawaban_peserta")
	_quizSesiUserJawaban.IDQuiz = field.NewInt32(tableName, "id_quiz")
	_quizSesiUserJawaban.IDUser = field.NewInt32(tableName, "id_user")
	_quizSesiUserJawaban.Kategori = field.NewString(tableName, "kategori")
	_quizSesiUserJawaban.Urutan = field.NewInt32(tableName, "urutan")
	_quizSesiUserJawaban.Jawaban = field.NewString(tableName, "jawaban")
	_quizSesiUserJawaban.Skor = field.NewInt32(tableName, "skor")

	_quizSesiUserJawaban.fillFieldMap()

	return _quizSesiUserJawaban
}

type quizSesiUserJawaban struct {
	quizSesiUserJawabanDo quizSesiUserJawabanDo

	ALL              field.Asterisk
	IDJawabanPeserta field.Int32
	IDQuiz           field.Int32
	IDUser           field.Int32
	Kategori         field.String
	Urutan           field.Int32
	Jawaban          field.String
	Skor             field.Int32

	fieldMap map[string]field.Expr
}

func (q quizSesiUserJawaban) Table(newTableName string) *quizSesiUserJawaban {
	q.quizSesiUserJawabanDo.UseTable(newTableName)
	return q.updateTableName(newTableName)
}

func (q quizSesiUserJawaban) As(alias string) *quizSesiUserJawaban {
	q.quizSesiUserJawabanDo.DO = *(q.quizSesiUserJawabanDo.As(alias).(*gen.DO))
	return q.updateTableName(alias)
}

func (q *quizSesiUserJawaban) updateTableName(table string) *quizSesiUserJawaban {
	q.ALL = field.NewAsterisk(table)
	q.IDJawabanPeserta = field.NewInt32(table, "id_jawaban_peserta")
	q.IDQuiz = field.NewInt32(table, "id_quiz")
	q.IDUser = field.NewInt32(table, "id_user")
	q.Kategori = field.NewString(table, "kategori")
	q.Urutan = field.NewInt32(table, "urutan")
	q.Jawaban = field.NewString(table, "jawaban")
	q.Skor = field.NewInt32(table, "skor")

	q.fillFieldMap()

	return q
}

func (q *quizSesiUserJawaban) WithContext(ctx context.Context) *quizSesiUserJawabanDo {
	return q.quizSesiUserJawabanDo.WithContext(ctx)
}

func (q quizSesiUserJawaban) TableName() string { return q.quizSesiUserJawabanDo.TableName() }

func (q quizSesiUserJawaban) Alias() string { return q.quizSesiUserJawabanDo.Alias() }

func (q quizSesiUserJawaban) Columns(cols ...field.Expr) gen.Columns {
	return q.quizSesiUserJawabanDo.Columns(cols...)
}

func (q *quizSesiUserJawaban) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := q.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (q *quizSesiUserJawaban) fillFieldMap() {
	q.fieldMap = make(map[string]field.Expr, 7)
	q.fieldMap["id_jawaban_peserta"] = q.IDJawabanPeserta
	q.fieldMap["id_quiz"] = q.IDQuiz
	q.fieldMap["id_user"] = q.IDUser
	q.fieldMap["kategori"] = q.Kategori
	q.fieldMap["urutan"] = q.Urutan
	q.fieldMap["jawaban"] = q.Jawaban
	q.fieldMap["skor"] = q.Skor
}

func (q quizSesiUserJawaban) clone(db *gorm.DB) quizSesiUserJawaban {
	q.quizSesiUserJawabanDo.ReplaceConnPool(db.Statement.ConnPool)
	return q
}

func (q quizSesiUserJawaban) replaceDB(db *gorm.DB) quizSesiUserJawaban {
	q.quizSesiUserJawabanDo.ReplaceDB(db)
	return q
}

type quizSesiUserJawabanDo struct{ gen.DO }

func (q quizSesiUserJawabanDo) Debug() *quizSesiUserJawabanDo {
	return q.withDO(q.DO.Debug())
}

func (q quizSesiUserJawabanDo) WithContext(ctx context.Context) *quizSesiUserJawabanDo {
	return q.withDO(q.DO.WithContext(ctx))
}

func (q quizSesiUserJawabanDo) ReadDB() *quizSesiUserJawabanDo {
	return q.Clauses(dbresolver.Read)
}

func (q quizSesiUserJawabanDo) WriteDB() *quizSesiUserJawabanDo {
	return q.Clauses(dbresolver.Write)
}

func (q quizSesiUserJawabanDo) Session(config *gorm.Session) *quizSesiUserJawabanDo {
	return q.withDO(q.DO.Session(config))
}

func (q quizSesiUserJawabanDo) Clauses(conds ...clause.Expression) *quizSesiUserJawabanDo {
	return q.withDO(q.DO.Clauses(conds...))
}

func (q quizSesiUserJawabanDo) Returning(value interface{}, columns ...string) *quizSesiUserJawabanDo {
	return q.withDO(q.DO.Returning(value, columns...))
}

func (q quizSesiUserJawabanDo) Not(conds ...gen.Condition) *quizSesiUserJawabanDo {
	return q.withDO(q.DO.Not(conds...))
}

func (q quizSesiUserJawabanDo) Or(conds ...gen.Condition) *quizSesiUserJawabanDo {
	return q.withDO(q.DO.Or(conds...))
}

func (q quizSesiUserJawabanDo) Select(conds ...field.Expr) *quizSesiUserJawabanDo {
	return q.withDO(q.DO.Select(conds...))
}

func (q quizSesiUserJawabanDo) Where(conds ...gen.Condition) *quizSesiUserJawabanDo {
	return q.withDO(q.DO.Where(conds...))
}

func (q quizSesiUserJawabanDo) Order(conds ...field.Expr) *quizSesiUserJawabanDo {
	return q.withDO(q.DO.Order(conds...))
}

func (q quizSesiUserJawabanDo) Distinct(cols ...field.Expr) *quizSesiUserJawabanDo {
	return q.withDO(q.DO.Distinct(cols...))
}

func (q quizSesiUserJawabanDo) Omit(cols ...field.Expr) *quizSesiUserJawabanDo {
	return q.withDO(q.DO.Omit(cols...))
}

func (q quizSesiUserJawabanDo) Join(table schema.Tabler, on ...field.Expr) *quizSesiUserJawabanDo {
	return q.withDO(q.DO.Join(table, on...))
}

func (q quizSesiUserJawabanDo) LeftJoin(table schema.Tabler, on ...field.Expr) *quizSesiUserJawabanDo {
	return q.withDO(q.DO.LeftJoin(table, on...))
}

func (q quizSesiUserJawabanDo) RightJoin(table schema.Tabler, on ...field.Expr) *quizSesiUserJawabanDo {
	return q.withDO(q.DO.RightJoin(table, on...))
}

func (q quizSesiUserJawabanDo) Group(cols ...field.Expr) *quizSesiUserJawabanDo {
	return q.withDO(q.DO.Group(cols...))
}

func (q quizSesiUserJawabanDo) Having(conds ...gen.Condition) *quizSesiUserJawabanDo {
	return q.withDO(q.DO.Having(conds...))
}

func (q quizSesiUserJawabanDo) Limit(limit int) *quizSesiUserJawabanDo {
	return q.withDO(q.DO.Limit(limit))
}

func (q quizSesiUserJawabanDo) Offset(offset int) *quizSesiUserJawabanDo {
	return q.withDO(q.DO.Offset(offset))
}

func (q quizSesiUserJawabanDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *quizSesiUserJawabanDo {
	return q.withDO(q.DO.Scopes(funcs...))
}

func (q quizSesiUserJawabanDo) Unscoped() *quizSesiUserJawabanDo {
	return q.withDO(q.DO.Unscoped())
}

func (q quizSesiUserJawabanDo) Create(values ...*entity.QuizSesiUserJawaban) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Create(values)
}

func (q quizSesiUserJawabanDo) CreateInBatches(values []*entity.QuizSesiUserJawaban, batchSize int) error {
	return q.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (q quizSesiUserJawabanDo) Save(values ...*entity.QuizSesiUserJawaban) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Save(values)
}

func (q quizSesiUserJawabanDo) First() (*entity.QuizSesiUserJawaban, error) {
	if result, err := q.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.QuizSesiUserJawaban), nil
	}
}

func (q quizSesiUserJawabanDo) Take() (*entity.QuizSesiUserJawaban, error) {
	if result, err := q.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.QuizSesiUserJawaban), nil
	}
}

func (q quizSesiUserJawabanDo) Last() (*entity.QuizSesiUserJawaban, error) {
	if result, err := q.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.QuizSesiUserJawaban), nil
	}
}

func (q quizSesiUserJawabanDo) Find() ([]*entity.QuizSesiUserJawaban, error) {
	result, err := q.DO.Find()
	return result.([]*entity.QuizSesiUserJawaban), err
}

func (q quizSesiUserJawabanDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.QuizSesiUserJawaban, err error) {
	buf := make([]*entity.QuizSesiUserJawaban, 0, batchSize)
	err = q.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (q quizSesiUserJawabanDo) FindInBatches(result *[]*entity.QuizSesiUserJawaban, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return q.DO.FindInBatches(result, batchSize, fc)
}

func (q quizSesiUserJawabanDo) Attrs(attrs ...field.AssignExpr) *quizSesiUserJawabanDo {
	return q.withDO(q.DO.Attrs(attrs...))
}

func (q quizSesiUserJawabanDo) Assign(attrs ...field.AssignExpr) *quizSesiUserJawabanDo {
	return q.withDO(q.DO.Assign(attrs...))
}

func (q quizSesiUserJawabanDo) Joins(fields ...field.RelationField) *quizSesiUserJawabanDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Joins(_f))
	}
	return &q
}

func (q quizSesiUserJawabanDo) Preload(fields ...field.RelationField) *quizSesiUserJawabanDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Preload(_f))
	}
	return &q
}

func (q quizSesiUserJawabanDo) FirstOrInit() (*entity.QuizSesiUserJawaban, error) {
	if result, err := q.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.QuizSesiUserJawaban), nil
	}
}

func (q quizSesiUserJawabanDo) FirstOrCreate() (*entity.QuizSesiUserJawaban, error) {
	if result, err := q.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.QuizSesiUserJawaban), nil
	}
}

func (q quizSesiUserJawabanDo) FindByPage(offset int, limit int) (result []*entity.QuizSesiUserJawaban, count int64, err error) {
	result, err = q.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = q.Offset(-1).Limit(-1).Count()
	return
}

func (q quizSesiUserJawabanDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = q.Count()
	if err != nil {
		return
	}

	err = q.Offset(offset).Limit(limit).Scan(result)
	return
}

func (q quizSesiUserJawabanDo) Scan(result interface{}) (err error) {
	return q.DO.Scan(result)
}

func (q quizSesiUserJawabanDo) Delete(models ...*entity.QuizSesiUserJawaban) (result gen.ResultInfo, err error) {
	return q.DO.Delete(models)
}

func (q *quizSesiUserJawabanDo) withDO(do gen.Dao) *quizSesiUserJawabanDo {
	q.DO = *do.(*gen.DO)
	return q
}
