// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package export

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"irwanka/sicerdas/utils/gen-model/entity"
)

func newRefRekomendasiAkhirSma(db *gorm.DB, opts ...gen.DOOption) refRekomendasiAkhirSma {
	_refRekomendasiAkhirSma := refRekomendasiAkhirSma{}

	_refRekomendasiAkhirSma.refRekomendasiAkhirSmaDo.UseDB(db, opts...)
	_refRekomendasiAkhirSma.refRekomendasiAkhirSmaDo.UseModel(&entity.RefRekomendasiAkhirSma{})

	tableName := _refRekomendasiAkhirSma.refRekomendasiAkhirSmaDo.TableName()
	_refRekomendasiAkhirSma.ALL = field.NewAsterisk(tableName)
	_refRekomendasiAkhirSma.ID = field.NewInt32(tableName, "id")
	_refRekomendasiAkhirSma.RekomMinat = field.NewString(tableName, "rekom_minat")
	_refRekomendasiAkhirSma.RekomSikapPelajaran = field.NewString(tableName, "rekom_sikap_pelajaran")
	_refRekomendasiAkhirSma.RekomTmi = field.NewString(tableName, "rekom_tmi")
	_refRekomendasiAkhirSma.RekomAkhir = field.NewString(tableName, "rekom_akhir")

	_refRekomendasiAkhirSma.fillFieldMap()

	return _refRekomendasiAkhirSma
}

type refRekomendasiAkhirSma struct {
	refRekomendasiAkhirSmaDo refRekomendasiAkhirSmaDo

	ALL                 field.Asterisk
	ID                  field.Int32
	RekomMinat          field.String
	RekomSikapPelajaran field.String
	RekomTmi            field.String
	RekomAkhir          field.String

	fieldMap map[string]field.Expr
}

func (r refRekomendasiAkhirSma) Table(newTableName string) *refRekomendasiAkhirSma {
	r.refRekomendasiAkhirSmaDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r refRekomendasiAkhirSma) As(alias string) *refRekomendasiAkhirSma {
	r.refRekomendasiAkhirSmaDo.DO = *(r.refRekomendasiAkhirSmaDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *refRekomendasiAkhirSma) updateTableName(table string) *refRekomendasiAkhirSma {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt32(table, "id")
	r.RekomMinat = field.NewString(table, "rekom_minat")
	r.RekomSikapPelajaran = field.NewString(table, "rekom_sikap_pelajaran")
	r.RekomTmi = field.NewString(table, "rekom_tmi")
	r.RekomAkhir = field.NewString(table, "rekom_akhir")

	r.fillFieldMap()

	return r
}

func (r *refRekomendasiAkhirSma) WithContext(ctx context.Context) *refRekomendasiAkhirSmaDo {
	return r.refRekomendasiAkhirSmaDo.WithContext(ctx)
}

func (r refRekomendasiAkhirSma) TableName() string { return r.refRekomendasiAkhirSmaDo.TableName() }

func (r refRekomendasiAkhirSma) Alias() string { return r.refRekomendasiAkhirSmaDo.Alias() }

func (r refRekomendasiAkhirSma) Columns(cols ...field.Expr) gen.Columns {
	return r.refRekomendasiAkhirSmaDo.Columns(cols...)
}

func (r *refRekomendasiAkhirSma) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *refRekomendasiAkhirSma) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 5)
	r.fieldMap["id"] = r.ID
	r.fieldMap["rekom_minat"] = r.RekomMinat
	r.fieldMap["rekom_sikap_pelajaran"] = r.RekomSikapPelajaran
	r.fieldMap["rekom_tmi"] = r.RekomTmi
	r.fieldMap["rekom_akhir"] = r.RekomAkhir
}

func (r refRekomendasiAkhirSma) clone(db *gorm.DB) refRekomendasiAkhirSma {
	r.refRekomendasiAkhirSmaDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r refRekomendasiAkhirSma) replaceDB(db *gorm.DB) refRekomendasiAkhirSma {
	r.refRekomendasiAkhirSmaDo.ReplaceDB(db)
	return r
}

type refRekomendasiAkhirSmaDo struct{ gen.DO }

func (r refRekomendasiAkhirSmaDo) Debug() *refRekomendasiAkhirSmaDo {
	return r.withDO(r.DO.Debug())
}

func (r refRekomendasiAkhirSmaDo) WithContext(ctx context.Context) *refRekomendasiAkhirSmaDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r refRekomendasiAkhirSmaDo) ReadDB() *refRekomendasiAkhirSmaDo {
	return r.Clauses(dbresolver.Read)
}

func (r refRekomendasiAkhirSmaDo) WriteDB() *refRekomendasiAkhirSmaDo {
	return r.Clauses(dbresolver.Write)
}

func (r refRekomendasiAkhirSmaDo) Session(config *gorm.Session) *refRekomendasiAkhirSmaDo {
	return r.withDO(r.DO.Session(config))
}

func (r refRekomendasiAkhirSmaDo) Clauses(conds ...clause.Expression) *refRekomendasiAkhirSmaDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r refRekomendasiAkhirSmaDo) Returning(value interface{}, columns ...string) *refRekomendasiAkhirSmaDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r refRekomendasiAkhirSmaDo) Not(conds ...gen.Condition) *refRekomendasiAkhirSmaDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r refRekomendasiAkhirSmaDo) Or(conds ...gen.Condition) *refRekomendasiAkhirSmaDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r refRekomendasiAkhirSmaDo) Select(conds ...field.Expr) *refRekomendasiAkhirSmaDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r refRekomendasiAkhirSmaDo) Where(conds ...gen.Condition) *refRekomendasiAkhirSmaDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r refRekomendasiAkhirSmaDo) Order(conds ...field.Expr) *refRekomendasiAkhirSmaDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r refRekomendasiAkhirSmaDo) Distinct(cols ...field.Expr) *refRekomendasiAkhirSmaDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r refRekomendasiAkhirSmaDo) Omit(cols ...field.Expr) *refRekomendasiAkhirSmaDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r refRekomendasiAkhirSmaDo) Join(table schema.Tabler, on ...field.Expr) *refRekomendasiAkhirSmaDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r refRekomendasiAkhirSmaDo) LeftJoin(table schema.Tabler, on ...field.Expr) *refRekomendasiAkhirSmaDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r refRekomendasiAkhirSmaDo) RightJoin(table schema.Tabler, on ...field.Expr) *refRekomendasiAkhirSmaDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r refRekomendasiAkhirSmaDo) Group(cols ...field.Expr) *refRekomendasiAkhirSmaDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r refRekomendasiAkhirSmaDo) Having(conds ...gen.Condition) *refRekomendasiAkhirSmaDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r refRekomendasiAkhirSmaDo) Limit(limit int) *refRekomendasiAkhirSmaDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r refRekomendasiAkhirSmaDo) Offset(offset int) *refRekomendasiAkhirSmaDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r refRekomendasiAkhirSmaDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *refRekomendasiAkhirSmaDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r refRekomendasiAkhirSmaDo) Unscoped() *refRekomendasiAkhirSmaDo {
	return r.withDO(r.DO.Unscoped())
}

func (r refRekomendasiAkhirSmaDo) Create(values ...*entity.RefRekomendasiAkhirSma) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r refRekomendasiAkhirSmaDo) CreateInBatches(values []*entity.RefRekomendasiAkhirSma, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r refRekomendasiAkhirSmaDo) Save(values ...*entity.RefRekomendasiAkhirSma) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r refRekomendasiAkhirSmaDo) First() (*entity.RefRekomendasiAkhirSma, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefRekomendasiAkhirSma), nil
	}
}

func (r refRekomendasiAkhirSmaDo) Take() (*entity.RefRekomendasiAkhirSma, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefRekomendasiAkhirSma), nil
	}
}

func (r refRekomendasiAkhirSmaDo) Last() (*entity.RefRekomendasiAkhirSma, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefRekomendasiAkhirSma), nil
	}
}

func (r refRekomendasiAkhirSmaDo) Find() ([]*entity.RefRekomendasiAkhirSma, error) {
	result, err := r.DO.Find()
	return result.([]*entity.RefRekomendasiAkhirSma), err
}

func (r refRekomendasiAkhirSmaDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RefRekomendasiAkhirSma, err error) {
	buf := make([]*entity.RefRekomendasiAkhirSma, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r refRekomendasiAkhirSmaDo) FindInBatches(result *[]*entity.RefRekomendasiAkhirSma, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r refRekomendasiAkhirSmaDo) Attrs(attrs ...field.AssignExpr) *refRekomendasiAkhirSmaDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r refRekomendasiAkhirSmaDo) Assign(attrs ...field.AssignExpr) *refRekomendasiAkhirSmaDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r refRekomendasiAkhirSmaDo) Joins(fields ...field.RelationField) *refRekomendasiAkhirSmaDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r refRekomendasiAkhirSmaDo) Preload(fields ...field.RelationField) *refRekomendasiAkhirSmaDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r refRekomendasiAkhirSmaDo) FirstOrInit() (*entity.RefRekomendasiAkhirSma, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefRekomendasiAkhirSma), nil
	}
}

func (r refRekomendasiAkhirSmaDo) FirstOrCreate() (*entity.RefRekomendasiAkhirSma, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefRekomendasiAkhirSma), nil
	}
}

func (r refRekomendasiAkhirSmaDo) FindByPage(offset int, limit int) (result []*entity.RefRekomendasiAkhirSma, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r refRekomendasiAkhirSmaDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r refRekomendasiAkhirSmaDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r refRekomendasiAkhirSmaDo) Delete(models ...*entity.RefRekomendasiAkhirSma) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *refRekomendasiAkhirSmaDo) withDO(do gen.Dao) *refRekomendasiAkhirSmaDo {
	r.DO = *do.(*gen.DO)
	return r
}
