// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package export

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"irwanka/sicerdas/utils/gen-model/entity"
)

func newRefKlasifikasiMinatSma(db *gorm.DB, opts ...gen.DOOption) refKlasifikasiMinatSma {
	_refKlasifikasiMinatSma := refKlasifikasiMinatSma{}

	_refKlasifikasiMinatSma.refKlasifikasiMinatSmaDo.UseDB(db, opts...)
	_refKlasifikasiMinatSma.refKlasifikasiMinatSmaDo.UseModel(&entity.RefKlasifikasiMinatSma{})

	tableName := _refKlasifikasiMinatSma.refKlasifikasiMinatSmaDo.TableName()
	_refKlasifikasiMinatSma.ALL = field.NewAsterisk(tableName)
	_refKlasifikasiMinatSma.ID = field.NewInt32(tableName, "id")
	_refKlasifikasiMinatSma.Skor = field.NewInt32(tableName, "skor")
	_refKlasifikasiMinatSma.Klasifikasi = field.NewString(tableName, "klasifikasi")

	_refKlasifikasiMinatSma.fillFieldMap()

	return _refKlasifikasiMinatSma
}

type refKlasifikasiMinatSma struct {
	refKlasifikasiMinatSmaDo refKlasifikasiMinatSmaDo

	ALL         field.Asterisk
	ID          field.Int32
	Skor        field.Int32
	Klasifikasi field.String

	fieldMap map[string]field.Expr
}

func (r refKlasifikasiMinatSma) Table(newTableName string) *refKlasifikasiMinatSma {
	r.refKlasifikasiMinatSmaDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r refKlasifikasiMinatSma) As(alias string) *refKlasifikasiMinatSma {
	r.refKlasifikasiMinatSmaDo.DO = *(r.refKlasifikasiMinatSmaDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *refKlasifikasiMinatSma) updateTableName(table string) *refKlasifikasiMinatSma {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt32(table, "id")
	r.Skor = field.NewInt32(table, "skor")
	r.Klasifikasi = field.NewString(table, "klasifikasi")

	r.fillFieldMap()

	return r
}

func (r *refKlasifikasiMinatSma) WithContext(ctx context.Context) *refKlasifikasiMinatSmaDo {
	return r.refKlasifikasiMinatSmaDo.WithContext(ctx)
}

func (r refKlasifikasiMinatSma) TableName() string { return r.refKlasifikasiMinatSmaDo.TableName() }

func (r refKlasifikasiMinatSma) Alias() string { return r.refKlasifikasiMinatSmaDo.Alias() }

func (r refKlasifikasiMinatSma) Columns(cols ...field.Expr) gen.Columns {
	return r.refKlasifikasiMinatSmaDo.Columns(cols...)
}

func (r *refKlasifikasiMinatSma) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *refKlasifikasiMinatSma) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 3)
	r.fieldMap["id"] = r.ID
	r.fieldMap["skor"] = r.Skor
	r.fieldMap["klasifikasi"] = r.Klasifikasi
}

func (r refKlasifikasiMinatSma) clone(db *gorm.DB) refKlasifikasiMinatSma {
	r.refKlasifikasiMinatSmaDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r refKlasifikasiMinatSma) replaceDB(db *gorm.DB) refKlasifikasiMinatSma {
	r.refKlasifikasiMinatSmaDo.ReplaceDB(db)
	return r
}

type refKlasifikasiMinatSmaDo struct{ gen.DO }

func (r refKlasifikasiMinatSmaDo) Debug() *refKlasifikasiMinatSmaDo {
	return r.withDO(r.DO.Debug())
}

func (r refKlasifikasiMinatSmaDo) WithContext(ctx context.Context) *refKlasifikasiMinatSmaDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r refKlasifikasiMinatSmaDo) ReadDB() *refKlasifikasiMinatSmaDo {
	return r.Clauses(dbresolver.Read)
}

func (r refKlasifikasiMinatSmaDo) WriteDB() *refKlasifikasiMinatSmaDo {
	return r.Clauses(dbresolver.Write)
}

func (r refKlasifikasiMinatSmaDo) Session(config *gorm.Session) *refKlasifikasiMinatSmaDo {
	return r.withDO(r.DO.Session(config))
}

func (r refKlasifikasiMinatSmaDo) Clauses(conds ...clause.Expression) *refKlasifikasiMinatSmaDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r refKlasifikasiMinatSmaDo) Returning(value interface{}, columns ...string) *refKlasifikasiMinatSmaDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r refKlasifikasiMinatSmaDo) Not(conds ...gen.Condition) *refKlasifikasiMinatSmaDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r refKlasifikasiMinatSmaDo) Or(conds ...gen.Condition) *refKlasifikasiMinatSmaDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r refKlasifikasiMinatSmaDo) Select(conds ...field.Expr) *refKlasifikasiMinatSmaDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r refKlasifikasiMinatSmaDo) Where(conds ...gen.Condition) *refKlasifikasiMinatSmaDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r refKlasifikasiMinatSmaDo) Order(conds ...field.Expr) *refKlasifikasiMinatSmaDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r refKlasifikasiMinatSmaDo) Distinct(cols ...field.Expr) *refKlasifikasiMinatSmaDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r refKlasifikasiMinatSmaDo) Omit(cols ...field.Expr) *refKlasifikasiMinatSmaDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r refKlasifikasiMinatSmaDo) Join(table schema.Tabler, on ...field.Expr) *refKlasifikasiMinatSmaDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r refKlasifikasiMinatSmaDo) LeftJoin(table schema.Tabler, on ...field.Expr) *refKlasifikasiMinatSmaDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r refKlasifikasiMinatSmaDo) RightJoin(table schema.Tabler, on ...field.Expr) *refKlasifikasiMinatSmaDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r refKlasifikasiMinatSmaDo) Group(cols ...field.Expr) *refKlasifikasiMinatSmaDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r refKlasifikasiMinatSmaDo) Having(conds ...gen.Condition) *refKlasifikasiMinatSmaDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r refKlasifikasiMinatSmaDo) Limit(limit int) *refKlasifikasiMinatSmaDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r refKlasifikasiMinatSmaDo) Offset(offset int) *refKlasifikasiMinatSmaDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r refKlasifikasiMinatSmaDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *refKlasifikasiMinatSmaDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r refKlasifikasiMinatSmaDo) Unscoped() *refKlasifikasiMinatSmaDo {
	return r.withDO(r.DO.Unscoped())
}

func (r refKlasifikasiMinatSmaDo) Create(values ...*entity.RefKlasifikasiMinatSma) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r refKlasifikasiMinatSmaDo) CreateInBatches(values []*entity.RefKlasifikasiMinatSma, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r refKlasifikasiMinatSmaDo) Save(values ...*entity.RefKlasifikasiMinatSma) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r refKlasifikasiMinatSmaDo) First() (*entity.RefKlasifikasiMinatSma, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefKlasifikasiMinatSma), nil
	}
}

func (r refKlasifikasiMinatSmaDo) Take() (*entity.RefKlasifikasiMinatSma, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefKlasifikasiMinatSma), nil
	}
}

func (r refKlasifikasiMinatSmaDo) Last() (*entity.RefKlasifikasiMinatSma, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefKlasifikasiMinatSma), nil
	}
}

func (r refKlasifikasiMinatSmaDo) Find() ([]*entity.RefKlasifikasiMinatSma, error) {
	result, err := r.DO.Find()
	return result.([]*entity.RefKlasifikasiMinatSma), err
}

func (r refKlasifikasiMinatSmaDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RefKlasifikasiMinatSma, err error) {
	buf := make([]*entity.RefKlasifikasiMinatSma, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r refKlasifikasiMinatSmaDo) FindInBatches(result *[]*entity.RefKlasifikasiMinatSma, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r refKlasifikasiMinatSmaDo) Attrs(attrs ...field.AssignExpr) *refKlasifikasiMinatSmaDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r refKlasifikasiMinatSmaDo) Assign(attrs ...field.AssignExpr) *refKlasifikasiMinatSmaDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r refKlasifikasiMinatSmaDo) Joins(fields ...field.RelationField) *refKlasifikasiMinatSmaDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r refKlasifikasiMinatSmaDo) Preload(fields ...field.RelationField) *refKlasifikasiMinatSmaDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r refKlasifikasiMinatSmaDo) FirstOrInit() (*entity.RefKlasifikasiMinatSma, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefKlasifikasiMinatSma), nil
	}
}

func (r refKlasifikasiMinatSmaDo) FirstOrCreate() (*entity.RefKlasifikasiMinatSma, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefKlasifikasiMinatSma), nil
	}
}

func (r refKlasifikasiMinatSmaDo) FindByPage(offset int, limit int) (result []*entity.RefKlasifikasiMinatSma, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r refKlasifikasiMinatSmaDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r refKlasifikasiMinatSmaDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r refKlasifikasiMinatSmaDo) Delete(models ...*entity.RefKlasifikasiMinatSma) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *refKlasifikasiMinatSmaDo) withDO(do gen.Dao) *refKlasifikasiMinatSmaDo {
	r.DO = *do.(*gen.DO)
	return r
}
