// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package export

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"irwanka/sicerdas/utils/gen-model/entity"
)

func newRefKlasifikasiKejiwaanDewasa(db *gorm.DB, opts ...gen.DOOption) refKlasifikasiKejiwaanDewasa {
	_refKlasifikasiKejiwaanDewasa := refKlasifikasiKejiwaanDewasa{}

	_refKlasifikasiKejiwaanDewasa.refKlasifikasiKejiwaanDewasaDo.UseDB(db, opts...)
	_refKlasifikasiKejiwaanDewasa.refKlasifikasiKejiwaanDewasaDo.UseModel(&entity.RefKlasifikasiKejiwaanDewasa{})

	tableName := _refKlasifikasiKejiwaanDewasa.refKlasifikasiKejiwaanDewasaDo.TableName()
	_refKlasifikasiKejiwaanDewasa.ALL = field.NewAsterisk(tableName)
	_refKlasifikasiKejiwaanDewasa.Nilai = field.NewInt16(tableName, "nilai")
	_refKlasifikasiKejiwaanDewasa.Keterangan = field.NewString(tableName, "keterangan")
	_refKlasifikasiKejiwaanDewasa.Tindakan = field.NewString(tableName, "tindakan")

	_refKlasifikasiKejiwaanDewasa.fillFieldMap()

	return _refKlasifikasiKejiwaanDewasa
}

type refKlasifikasiKejiwaanDewasa struct {
	refKlasifikasiKejiwaanDewasaDo refKlasifikasiKejiwaanDewasaDo

	ALL        field.Asterisk
	Nilai      field.Int16
	Keterangan field.String
	Tindakan   field.String

	fieldMap map[string]field.Expr
}

func (r refKlasifikasiKejiwaanDewasa) Table(newTableName string) *refKlasifikasiKejiwaanDewasa {
	r.refKlasifikasiKejiwaanDewasaDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r refKlasifikasiKejiwaanDewasa) As(alias string) *refKlasifikasiKejiwaanDewasa {
	r.refKlasifikasiKejiwaanDewasaDo.DO = *(r.refKlasifikasiKejiwaanDewasaDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *refKlasifikasiKejiwaanDewasa) updateTableName(table string) *refKlasifikasiKejiwaanDewasa {
	r.ALL = field.NewAsterisk(table)
	r.Nilai = field.NewInt16(table, "nilai")
	r.Keterangan = field.NewString(table, "keterangan")
	r.Tindakan = field.NewString(table, "tindakan")

	r.fillFieldMap()

	return r
}

func (r *refKlasifikasiKejiwaanDewasa) WithContext(ctx context.Context) *refKlasifikasiKejiwaanDewasaDo {
	return r.refKlasifikasiKejiwaanDewasaDo.WithContext(ctx)
}

func (r refKlasifikasiKejiwaanDewasa) TableName() string {
	return r.refKlasifikasiKejiwaanDewasaDo.TableName()
}

func (r refKlasifikasiKejiwaanDewasa) Alias() string { return r.refKlasifikasiKejiwaanDewasaDo.Alias() }

func (r refKlasifikasiKejiwaanDewasa) Columns(cols ...field.Expr) gen.Columns {
	return r.refKlasifikasiKejiwaanDewasaDo.Columns(cols...)
}

func (r *refKlasifikasiKejiwaanDewasa) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *refKlasifikasiKejiwaanDewasa) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 3)
	r.fieldMap["nilai"] = r.Nilai
	r.fieldMap["keterangan"] = r.Keterangan
	r.fieldMap["tindakan"] = r.Tindakan
}

func (r refKlasifikasiKejiwaanDewasa) clone(db *gorm.DB) refKlasifikasiKejiwaanDewasa {
	r.refKlasifikasiKejiwaanDewasaDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r refKlasifikasiKejiwaanDewasa) replaceDB(db *gorm.DB) refKlasifikasiKejiwaanDewasa {
	r.refKlasifikasiKejiwaanDewasaDo.ReplaceDB(db)
	return r
}

type refKlasifikasiKejiwaanDewasaDo struct{ gen.DO }

func (r refKlasifikasiKejiwaanDewasaDo) Debug() *refKlasifikasiKejiwaanDewasaDo {
	return r.withDO(r.DO.Debug())
}

func (r refKlasifikasiKejiwaanDewasaDo) WithContext(ctx context.Context) *refKlasifikasiKejiwaanDewasaDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r refKlasifikasiKejiwaanDewasaDo) ReadDB() *refKlasifikasiKejiwaanDewasaDo {
	return r.Clauses(dbresolver.Read)
}

func (r refKlasifikasiKejiwaanDewasaDo) WriteDB() *refKlasifikasiKejiwaanDewasaDo {
	return r.Clauses(dbresolver.Write)
}

func (r refKlasifikasiKejiwaanDewasaDo) Session(config *gorm.Session) *refKlasifikasiKejiwaanDewasaDo {
	return r.withDO(r.DO.Session(config))
}

func (r refKlasifikasiKejiwaanDewasaDo) Clauses(conds ...clause.Expression) *refKlasifikasiKejiwaanDewasaDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r refKlasifikasiKejiwaanDewasaDo) Returning(value interface{}, columns ...string) *refKlasifikasiKejiwaanDewasaDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r refKlasifikasiKejiwaanDewasaDo) Not(conds ...gen.Condition) *refKlasifikasiKejiwaanDewasaDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r refKlasifikasiKejiwaanDewasaDo) Or(conds ...gen.Condition) *refKlasifikasiKejiwaanDewasaDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r refKlasifikasiKejiwaanDewasaDo) Select(conds ...field.Expr) *refKlasifikasiKejiwaanDewasaDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r refKlasifikasiKejiwaanDewasaDo) Where(conds ...gen.Condition) *refKlasifikasiKejiwaanDewasaDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r refKlasifikasiKejiwaanDewasaDo) Order(conds ...field.Expr) *refKlasifikasiKejiwaanDewasaDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r refKlasifikasiKejiwaanDewasaDo) Distinct(cols ...field.Expr) *refKlasifikasiKejiwaanDewasaDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r refKlasifikasiKejiwaanDewasaDo) Omit(cols ...field.Expr) *refKlasifikasiKejiwaanDewasaDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r refKlasifikasiKejiwaanDewasaDo) Join(table schema.Tabler, on ...field.Expr) *refKlasifikasiKejiwaanDewasaDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r refKlasifikasiKejiwaanDewasaDo) LeftJoin(table schema.Tabler, on ...field.Expr) *refKlasifikasiKejiwaanDewasaDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r refKlasifikasiKejiwaanDewasaDo) RightJoin(table schema.Tabler, on ...field.Expr) *refKlasifikasiKejiwaanDewasaDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r refKlasifikasiKejiwaanDewasaDo) Group(cols ...field.Expr) *refKlasifikasiKejiwaanDewasaDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r refKlasifikasiKejiwaanDewasaDo) Having(conds ...gen.Condition) *refKlasifikasiKejiwaanDewasaDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r refKlasifikasiKejiwaanDewasaDo) Limit(limit int) *refKlasifikasiKejiwaanDewasaDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r refKlasifikasiKejiwaanDewasaDo) Offset(offset int) *refKlasifikasiKejiwaanDewasaDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r refKlasifikasiKejiwaanDewasaDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *refKlasifikasiKejiwaanDewasaDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r refKlasifikasiKejiwaanDewasaDo) Unscoped() *refKlasifikasiKejiwaanDewasaDo {
	return r.withDO(r.DO.Unscoped())
}

func (r refKlasifikasiKejiwaanDewasaDo) Create(values ...*entity.RefKlasifikasiKejiwaanDewasa) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r refKlasifikasiKejiwaanDewasaDo) CreateInBatches(values []*entity.RefKlasifikasiKejiwaanDewasa, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r refKlasifikasiKejiwaanDewasaDo) Save(values ...*entity.RefKlasifikasiKejiwaanDewasa) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r refKlasifikasiKejiwaanDewasaDo) First() (*entity.RefKlasifikasiKejiwaanDewasa, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefKlasifikasiKejiwaanDewasa), nil
	}
}

func (r refKlasifikasiKejiwaanDewasaDo) Take() (*entity.RefKlasifikasiKejiwaanDewasa, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefKlasifikasiKejiwaanDewasa), nil
	}
}

func (r refKlasifikasiKejiwaanDewasaDo) Last() (*entity.RefKlasifikasiKejiwaanDewasa, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefKlasifikasiKejiwaanDewasa), nil
	}
}

func (r refKlasifikasiKejiwaanDewasaDo) Find() ([]*entity.RefKlasifikasiKejiwaanDewasa, error) {
	result, err := r.DO.Find()
	return result.([]*entity.RefKlasifikasiKejiwaanDewasa), err
}

func (r refKlasifikasiKejiwaanDewasaDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RefKlasifikasiKejiwaanDewasa, err error) {
	buf := make([]*entity.RefKlasifikasiKejiwaanDewasa, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r refKlasifikasiKejiwaanDewasaDo) FindInBatches(result *[]*entity.RefKlasifikasiKejiwaanDewasa, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r refKlasifikasiKejiwaanDewasaDo) Attrs(attrs ...field.AssignExpr) *refKlasifikasiKejiwaanDewasaDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r refKlasifikasiKejiwaanDewasaDo) Assign(attrs ...field.AssignExpr) *refKlasifikasiKejiwaanDewasaDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r refKlasifikasiKejiwaanDewasaDo) Joins(fields ...field.RelationField) *refKlasifikasiKejiwaanDewasaDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r refKlasifikasiKejiwaanDewasaDo) Preload(fields ...field.RelationField) *refKlasifikasiKejiwaanDewasaDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r refKlasifikasiKejiwaanDewasaDo) FirstOrInit() (*entity.RefKlasifikasiKejiwaanDewasa, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefKlasifikasiKejiwaanDewasa), nil
	}
}

func (r refKlasifikasiKejiwaanDewasaDo) FirstOrCreate() (*entity.RefKlasifikasiKejiwaanDewasa, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefKlasifikasiKejiwaanDewasa), nil
	}
}

func (r refKlasifikasiKejiwaanDewasaDo) FindByPage(offset int, limit int) (result []*entity.RefKlasifikasiKejiwaanDewasa, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r refKlasifikasiKejiwaanDewasaDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r refKlasifikasiKejiwaanDewasaDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r refKlasifikasiKejiwaanDewasaDo) Delete(models ...*entity.RefKlasifikasiKejiwaanDewasa) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *refKlasifikasiKejiwaanDewasaDo) withDO(do gen.Dao) *refKlasifikasiKejiwaanDewasaDo {
	r.DO = *do.(*gen.DO)
	return r
}
