// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package export

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"irwanka/sicerdas/utils/gen-model/entity"
)

func newRefSkorGayaBelajar(db *gorm.DB, opts ...gen.DOOption) refSkorGayaBelajar {
	_refSkorGayaBelajar := refSkorGayaBelajar{}

	_refSkorGayaBelajar.refSkorGayaBelajarDo.UseDB(db, opts...)
	_refSkorGayaBelajar.refSkorGayaBelajarDo.UseModel(&entity.RefSkorGayaBelajar{})

	tableName := _refSkorGayaBelajar.refSkorGayaBelajarDo.TableName()
	_refSkorGayaBelajar.ALL = field.NewAsterisk(tableName)
	_refSkorGayaBelajar.Skor = field.NewInt16(tableName, "skor")
	_refSkorGayaBelajar.Klasifikasi = field.NewString(tableName, "klasifikasi")

	_refSkorGayaBelajar.fillFieldMap()

	return _refSkorGayaBelajar
}

type refSkorGayaBelajar struct {
	refSkorGayaBelajarDo refSkorGayaBelajarDo

	ALL         field.Asterisk
	Skor        field.Int16
	Klasifikasi field.String

	fieldMap map[string]field.Expr
}

func (r refSkorGayaBelajar) Table(newTableName string) *refSkorGayaBelajar {
	r.refSkorGayaBelajarDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r refSkorGayaBelajar) As(alias string) *refSkorGayaBelajar {
	r.refSkorGayaBelajarDo.DO = *(r.refSkorGayaBelajarDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *refSkorGayaBelajar) updateTableName(table string) *refSkorGayaBelajar {
	r.ALL = field.NewAsterisk(table)
	r.Skor = field.NewInt16(table, "skor")
	r.Klasifikasi = field.NewString(table, "klasifikasi")

	r.fillFieldMap()

	return r
}

func (r *refSkorGayaBelajar) WithContext(ctx context.Context) *refSkorGayaBelajarDo {
	return r.refSkorGayaBelajarDo.WithContext(ctx)
}

func (r refSkorGayaBelajar) TableName() string { return r.refSkorGayaBelajarDo.TableName() }

func (r refSkorGayaBelajar) Alias() string { return r.refSkorGayaBelajarDo.Alias() }

func (r refSkorGayaBelajar) Columns(cols ...field.Expr) gen.Columns {
	return r.refSkorGayaBelajarDo.Columns(cols...)
}

func (r *refSkorGayaBelajar) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *refSkorGayaBelajar) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 2)
	r.fieldMap["skor"] = r.Skor
	r.fieldMap["klasifikasi"] = r.Klasifikasi
}

func (r refSkorGayaBelajar) clone(db *gorm.DB) refSkorGayaBelajar {
	r.refSkorGayaBelajarDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r refSkorGayaBelajar) replaceDB(db *gorm.DB) refSkorGayaBelajar {
	r.refSkorGayaBelajarDo.ReplaceDB(db)
	return r
}

type refSkorGayaBelajarDo struct{ gen.DO }

func (r refSkorGayaBelajarDo) Debug() *refSkorGayaBelajarDo {
	return r.withDO(r.DO.Debug())
}

func (r refSkorGayaBelajarDo) WithContext(ctx context.Context) *refSkorGayaBelajarDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r refSkorGayaBelajarDo) ReadDB() *refSkorGayaBelajarDo {
	return r.Clauses(dbresolver.Read)
}

func (r refSkorGayaBelajarDo) WriteDB() *refSkorGayaBelajarDo {
	return r.Clauses(dbresolver.Write)
}

func (r refSkorGayaBelajarDo) Session(config *gorm.Session) *refSkorGayaBelajarDo {
	return r.withDO(r.DO.Session(config))
}

func (r refSkorGayaBelajarDo) Clauses(conds ...clause.Expression) *refSkorGayaBelajarDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r refSkorGayaBelajarDo) Returning(value interface{}, columns ...string) *refSkorGayaBelajarDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r refSkorGayaBelajarDo) Not(conds ...gen.Condition) *refSkorGayaBelajarDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r refSkorGayaBelajarDo) Or(conds ...gen.Condition) *refSkorGayaBelajarDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r refSkorGayaBelajarDo) Select(conds ...field.Expr) *refSkorGayaBelajarDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r refSkorGayaBelajarDo) Where(conds ...gen.Condition) *refSkorGayaBelajarDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r refSkorGayaBelajarDo) Order(conds ...field.Expr) *refSkorGayaBelajarDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r refSkorGayaBelajarDo) Distinct(cols ...field.Expr) *refSkorGayaBelajarDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r refSkorGayaBelajarDo) Omit(cols ...field.Expr) *refSkorGayaBelajarDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r refSkorGayaBelajarDo) Join(table schema.Tabler, on ...field.Expr) *refSkorGayaBelajarDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r refSkorGayaBelajarDo) LeftJoin(table schema.Tabler, on ...field.Expr) *refSkorGayaBelajarDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r refSkorGayaBelajarDo) RightJoin(table schema.Tabler, on ...field.Expr) *refSkorGayaBelajarDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r refSkorGayaBelajarDo) Group(cols ...field.Expr) *refSkorGayaBelajarDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r refSkorGayaBelajarDo) Having(conds ...gen.Condition) *refSkorGayaBelajarDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r refSkorGayaBelajarDo) Limit(limit int) *refSkorGayaBelajarDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r refSkorGayaBelajarDo) Offset(offset int) *refSkorGayaBelajarDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r refSkorGayaBelajarDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *refSkorGayaBelajarDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r refSkorGayaBelajarDo) Unscoped() *refSkorGayaBelajarDo {
	return r.withDO(r.DO.Unscoped())
}

func (r refSkorGayaBelajarDo) Create(values ...*entity.RefSkorGayaBelajar) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r refSkorGayaBelajarDo) CreateInBatches(values []*entity.RefSkorGayaBelajar, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r refSkorGayaBelajarDo) Save(values ...*entity.RefSkorGayaBelajar) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r refSkorGayaBelajarDo) First() (*entity.RefSkorGayaBelajar, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefSkorGayaBelajar), nil
	}
}

func (r refSkorGayaBelajarDo) Take() (*entity.RefSkorGayaBelajar, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefSkorGayaBelajar), nil
	}
}

func (r refSkorGayaBelajarDo) Last() (*entity.RefSkorGayaBelajar, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefSkorGayaBelajar), nil
	}
}

func (r refSkorGayaBelajarDo) Find() ([]*entity.RefSkorGayaBelajar, error) {
	result, err := r.DO.Find()
	return result.([]*entity.RefSkorGayaBelajar), err
}

func (r refSkorGayaBelajarDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RefSkorGayaBelajar, err error) {
	buf := make([]*entity.RefSkorGayaBelajar, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r refSkorGayaBelajarDo) FindInBatches(result *[]*entity.RefSkorGayaBelajar, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r refSkorGayaBelajarDo) Attrs(attrs ...field.AssignExpr) *refSkorGayaBelajarDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r refSkorGayaBelajarDo) Assign(attrs ...field.AssignExpr) *refSkorGayaBelajarDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r refSkorGayaBelajarDo) Joins(fields ...field.RelationField) *refSkorGayaBelajarDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r refSkorGayaBelajarDo) Preload(fields ...field.RelationField) *refSkorGayaBelajarDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r refSkorGayaBelajarDo) FirstOrInit() (*entity.RefSkorGayaBelajar, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefSkorGayaBelajar), nil
	}
}

func (r refSkorGayaBelajarDo) FirstOrCreate() (*entity.RefSkorGayaBelajar, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefSkorGayaBelajar), nil
	}
}

func (r refSkorGayaBelajarDo) FindByPage(offset int, limit int) (result []*entity.RefSkorGayaBelajar, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r refSkorGayaBelajarDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r refSkorGayaBelajarDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r refSkorGayaBelajarDo) Delete(models ...*entity.RefSkorGayaBelajar) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *refSkorGayaBelajarDo) withDO(do gen.Dao) *refSkorGayaBelajarDo {
	r.DO = *do.(*gen.DO)
	return r
}
