// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package export

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"irwanka/sicerdas/utils/gen-model/entity"
)

func newRefSkalaKdPenalaranKuantitatif(db *gorm.DB, opts ...gen.DOOption) refSkalaKdPenalaranKuantitatif {
	_refSkalaKdPenalaranKuantitatif := refSkalaKdPenalaranKuantitatif{}

	_refSkalaKdPenalaranKuantitatif.refSkalaKdPenalaranKuantitatifDo.UseDB(db, opts...)
	_refSkalaKdPenalaranKuantitatif.refSkalaKdPenalaranKuantitatifDo.UseModel(&entity.RefSkalaKdPenalaranKuantitatif{})

	tableName := _refSkalaKdPenalaranKuantitatif.refSkalaKdPenalaranKuantitatifDo.TableName()
	_refSkalaKdPenalaranKuantitatif.ALL = field.NewAsterisk(tableName)
	_refSkalaKdPenalaranKuantitatif.ID = field.NewInt32(tableName, "id")
	_refSkalaKdPenalaranKuantitatif.Skor = field.NewInt32(tableName, "skor")
	_refSkalaKdPenalaranKuantitatif.Klasifikasi = field.NewString(tableName, "klasifikasi")

	_refSkalaKdPenalaranKuantitatif.fillFieldMap()

	return _refSkalaKdPenalaranKuantitatif
}

type refSkalaKdPenalaranKuantitatif struct {
	refSkalaKdPenalaranKuantitatifDo refSkalaKdPenalaranKuantitatifDo

	ALL         field.Asterisk
	ID          field.Int32
	Skor        field.Int32
	Klasifikasi field.String

	fieldMap map[string]field.Expr
}

func (r refSkalaKdPenalaranKuantitatif) Table(newTableName string) *refSkalaKdPenalaranKuantitatif {
	r.refSkalaKdPenalaranKuantitatifDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r refSkalaKdPenalaranKuantitatif) As(alias string) *refSkalaKdPenalaranKuantitatif {
	r.refSkalaKdPenalaranKuantitatifDo.DO = *(r.refSkalaKdPenalaranKuantitatifDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *refSkalaKdPenalaranKuantitatif) updateTableName(table string) *refSkalaKdPenalaranKuantitatif {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt32(table, "id")
	r.Skor = field.NewInt32(table, "skor")
	r.Klasifikasi = field.NewString(table, "klasifikasi")

	r.fillFieldMap()

	return r
}

func (r *refSkalaKdPenalaranKuantitatif) WithContext(ctx context.Context) *refSkalaKdPenalaranKuantitatifDo {
	return r.refSkalaKdPenalaranKuantitatifDo.WithContext(ctx)
}

func (r refSkalaKdPenalaranKuantitatif) TableName() string {
	return r.refSkalaKdPenalaranKuantitatifDo.TableName()
}

func (r refSkalaKdPenalaranKuantitatif) Alias() string {
	return r.refSkalaKdPenalaranKuantitatifDo.Alias()
}

func (r refSkalaKdPenalaranKuantitatif) Columns(cols ...field.Expr) gen.Columns {
	return r.refSkalaKdPenalaranKuantitatifDo.Columns(cols...)
}

func (r *refSkalaKdPenalaranKuantitatif) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *refSkalaKdPenalaranKuantitatif) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 3)
	r.fieldMap["id"] = r.ID
	r.fieldMap["skor"] = r.Skor
	r.fieldMap["klasifikasi"] = r.Klasifikasi
}

func (r refSkalaKdPenalaranKuantitatif) clone(db *gorm.DB) refSkalaKdPenalaranKuantitatif {
	r.refSkalaKdPenalaranKuantitatifDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r refSkalaKdPenalaranKuantitatif) replaceDB(db *gorm.DB) refSkalaKdPenalaranKuantitatif {
	r.refSkalaKdPenalaranKuantitatifDo.ReplaceDB(db)
	return r
}

type refSkalaKdPenalaranKuantitatifDo struct{ gen.DO }

func (r refSkalaKdPenalaranKuantitatifDo) Debug() *refSkalaKdPenalaranKuantitatifDo {
	return r.withDO(r.DO.Debug())
}

func (r refSkalaKdPenalaranKuantitatifDo) WithContext(ctx context.Context) *refSkalaKdPenalaranKuantitatifDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r refSkalaKdPenalaranKuantitatifDo) ReadDB() *refSkalaKdPenalaranKuantitatifDo {
	return r.Clauses(dbresolver.Read)
}

func (r refSkalaKdPenalaranKuantitatifDo) WriteDB() *refSkalaKdPenalaranKuantitatifDo {
	return r.Clauses(dbresolver.Write)
}

func (r refSkalaKdPenalaranKuantitatifDo) Session(config *gorm.Session) *refSkalaKdPenalaranKuantitatifDo {
	return r.withDO(r.DO.Session(config))
}

func (r refSkalaKdPenalaranKuantitatifDo) Clauses(conds ...clause.Expression) *refSkalaKdPenalaranKuantitatifDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r refSkalaKdPenalaranKuantitatifDo) Returning(value interface{}, columns ...string) *refSkalaKdPenalaranKuantitatifDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r refSkalaKdPenalaranKuantitatifDo) Not(conds ...gen.Condition) *refSkalaKdPenalaranKuantitatifDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r refSkalaKdPenalaranKuantitatifDo) Or(conds ...gen.Condition) *refSkalaKdPenalaranKuantitatifDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r refSkalaKdPenalaranKuantitatifDo) Select(conds ...field.Expr) *refSkalaKdPenalaranKuantitatifDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r refSkalaKdPenalaranKuantitatifDo) Where(conds ...gen.Condition) *refSkalaKdPenalaranKuantitatifDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r refSkalaKdPenalaranKuantitatifDo) Order(conds ...field.Expr) *refSkalaKdPenalaranKuantitatifDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r refSkalaKdPenalaranKuantitatifDo) Distinct(cols ...field.Expr) *refSkalaKdPenalaranKuantitatifDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r refSkalaKdPenalaranKuantitatifDo) Omit(cols ...field.Expr) *refSkalaKdPenalaranKuantitatifDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r refSkalaKdPenalaranKuantitatifDo) Join(table schema.Tabler, on ...field.Expr) *refSkalaKdPenalaranKuantitatifDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r refSkalaKdPenalaranKuantitatifDo) LeftJoin(table schema.Tabler, on ...field.Expr) *refSkalaKdPenalaranKuantitatifDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r refSkalaKdPenalaranKuantitatifDo) RightJoin(table schema.Tabler, on ...field.Expr) *refSkalaKdPenalaranKuantitatifDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r refSkalaKdPenalaranKuantitatifDo) Group(cols ...field.Expr) *refSkalaKdPenalaranKuantitatifDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r refSkalaKdPenalaranKuantitatifDo) Having(conds ...gen.Condition) *refSkalaKdPenalaranKuantitatifDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r refSkalaKdPenalaranKuantitatifDo) Limit(limit int) *refSkalaKdPenalaranKuantitatifDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r refSkalaKdPenalaranKuantitatifDo) Offset(offset int) *refSkalaKdPenalaranKuantitatifDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r refSkalaKdPenalaranKuantitatifDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *refSkalaKdPenalaranKuantitatifDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r refSkalaKdPenalaranKuantitatifDo) Unscoped() *refSkalaKdPenalaranKuantitatifDo {
	return r.withDO(r.DO.Unscoped())
}

func (r refSkalaKdPenalaranKuantitatifDo) Create(values ...*entity.RefSkalaKdPenalaranKuantitatif) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r refSkalaKdPenalaranKuantitatifDo) CreateInBatches(values []*entity.RefSkalaKdPenalaranKuantitatif, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r refSkalaKdPenalaranKuantitatifDo) Save(values ...*entity.RefSkalaKdPenalaranKuantitatif) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r refSkalaKdPenalaranKuantitatifDo) First() (*entity.RefSkalaKdPenalaranKuantitatif, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefSkalaKdPenalaranKuantitatif), nil
	}
}

func (r refSkalaKdPenalaranKuantitatifDo) Take() (*entity.RefSkalaKdPenalaranKuantitatif, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefSkalaKdPenalaranKuantitatif), nil
	}
}

func (r refSkalaKdPenalaranKuantitatifDo) Last() (*entity.RefSkalaKdPenalaranKuantitatif, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefSkalaKdPenalaranKuantitatif), nil
	}
}

func (r refSkalaKdPenalaranKuantitatifDo) Find() ([]*entity.RefSkalaKdPenalaranKuantitatif, error) {
	result, err := r.DO.Find()
	return result.([]*entity.RefSkalaKdPenalaranKuantitatif), err
}

func (r refSkalaKdPenalaranKuantitatifDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RefSkalaKdPenalaranKuantitatif, err error) {
	buf := make([]*entity.RefSkalaKdPenalaranKuantitatif, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r refSkalaKdPenalaranKuantitatifDo) FindInBatches(result *[]*entity.RefSkalaKdPenalaranKuantitatif, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r refSkalaKdPenalaranKuantitatifDo) Attrs(attrs ...field.AssignExpr) *refSkalaKdPenalaranKuantitatifDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r refSkalaKdPenalaranKuantitatifDo) Assign(attrs ...field.AssignExpr) *refSkalaKdPenalaranKuantitatifDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r refSkalaKdPenalaranKuantitatifDo) Joins(fields ...field.RelationField) *refSkalaKdPenalaranKuantitatifDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r refSkalaKdPenalaranKuantitatifDo) Preload(fields ...field.RelationField) *refSkalaKdPenalaranKuantitatifDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r refSkalaKdPenalaranKuantitatifDo) FirstOrInit() (*entity.RefSkalaKdPenalaranKuantitatif, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefSkalaKdPenalaranKuantitatif), nil
	}
}

func (r refSkalaKdPenalaranKuantitatifDo) FirstOrCreate() (*entity.RefSkalaKdPenalaranKuantitatif, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefSkalaKdPenalaranKuantitatif), nil
	}
}

func (r refSkalaKdPenalaranKuantitatifDo) FindByPage(offset int, limit int) (result []*entity.RefSkalaKdPenalaranKuantitatif, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r refSkalaKdPenalaranKuantitatifDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r refSkalaKdPenalaranKuantitatifDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r refSkalaKdPenalaranKuantitatifDo) Delete(models ...*entity.RefSkalaKdPenalaranKuantitatif) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *refSkalaKdPenalaranKuantitatifDo) withDO(do gen.Dao) *refSkalaKdPenalaranKuantitatifDo {
	r.DO = *do.(*gen.DO)
	return r
}
