// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package export

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"irwanka/sicerdas/utils/gen-model/entity"
)

func newRefKonversiIq105(db *gorm.DB, opts ...gen.DOOption) refKonversiIq105 {
	_refKonversiIq105 := refKonversiIq105{}

	_refKonversiIq105.refKonversiIq105Do.UseDB(db, opts...)
	_refKonversiIq105.refKonversiIq105Do.UseModel(&entity.RefKonversiIq105{})

	tableName := _refKonversiIq105.refKonversiIq105Do.TableName()
	_refKonversiIq105.ALL = field.NewAsterisk(tableName)
	_refKonversiIq105.ID = field.NewInt32(tableName, "id")
	_refKonversiIq105.SkorX = field.NewInt32(tableName, "skor_x")
	_refKonversiIq105.TotIq = field.NewFloat32(tableName, "tot_iq")
	_refKonversiIq105.Klasifikasi = field.NewString(tableName, "klasifikasi")

	_refKonversiIq105.fillFieldMap()

	return _refKonversiIq105
}

type refKonversiIq105 struct {
	refKonversiIq105Do refKonversiIq105Do

	ALL         field.Asterisk
	ID          field.Int32
	SkorX       field.Int32
	TotIq       field.Float32
	Klasifikasi field.String

	fieldMap map[string]field.Expr
}

func (r refKonversiIq105) Table(newTableName string) *refKonversiIq105 {
	r.refKonversiIq105Do.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r refKonversiIq105) As(alias string) *refKonversiIq105 {
	r.refKonversiIq105Do.DO = *(r.refKonversiIq105Do.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *refKonversiIq105) updateTableName(table string) *refKonversiIq105 {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt32(table, "id")
	r.SkorX = field.NewInt32(table, "skor_x")
	r.TotIq = field.NewFloat32(table, "tot_iq")
	r.Klasifikasi = field.NewString(table, "klasifikasi")

	r.fillFieldMap()

	return r
}

func (r *refKonversiIq105) WithContext(ctx context.Context) *refKonversiIq105Do {
	return r.refKonversiIq105Do.WithContext(ctx)
}

func (r refKonversiIq105) TableName() string { return r.refKonversiIq105Do.TableName() }

func (r refKonversiIq105) Alias() string { return r.refKonversiIq105Do.Alias() }

func (r refKonversiIq105) Columns(cols ...field.Expr) gen.Columns {
	return r.refKonversiIq105Do.Columns(cols...)
}

func (r *refKonversiIq105) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *refKonversiIq105) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 4)
	r.fieldMap["id"] = r.ID
	r.fieldMap["skor_x"] = r.SkorX
	r.fieldMap["tot_iq"] = r.TotIq
	r.fieldMap["klasifikasi"] = r.Klasifikasi
}

func (r refKonversiIq105) clone(db *gorm.DB) refKonversiIq105 {
	r.refKonversiIq105Do.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r refKonversiIq105) replaceDB(db *gorm.DB) refKonversiIq105 {
	r.refKonversiIq105Do.ReplaceDB(db)
	return r
}

type refKonversiIq105Do struct{ gen.DO }

func (r refKonversiIq105Do) Debug() *refKonversiIq105Do {
	return r.withDO(r.DO.Debug())
}

func (r refKonversiIq105Do) WithContext(ctx context.Context) *refKonversiIq105Do {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r refKonversiIq105Do) ReadDB() *refKonversiIq105Do {
	return r.Clauses(dbresolver.Read)
}

func (r refKonversiIq105Do) WriteDB() *refKonversiIq105Do {
	return r.Clauses(dbresolver.Write)
}

func (r refKonversiIq105Do) Session(config *gorm.Session) *refKonversiIq105Do {
	return r.withDO(r.DO.Session(config))
}

func (r refKonversiIq105Do) Clauses(conds ...clause.Expression) *refKonversiIq105Do {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r refKonversiIq105Do) Returning(value interface{}, columns ...string) *refKonversiIq105Do {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r refKonversiIq105Do) Not(conds ...gen.Condition) *refKonversiIq105Do {
	return r.withDO(r.DO.Not(conds...))
}

func (r refKonversiIq105Do) Or(conds ...gen.Condition) *refKonversiIq105Do {
	return r.withDO(r.DO.Or(conds...))
}

func (r refKonversiIq105Do) Select(conds ...field.Expr) *refKonversiIq105Do {
	return r.withDO(r.DO.Select(conds...))
}

func (r refKonversiIq105Do) Where(conds ...gen.Condition) *refKonversiIq105Do {
	return r.withDO(r.DO.Where(conds...))
}

func (r refKonversiIq105Do) Order(conds ...field.Expr) *refKonversiIq105Do {
	return r.withDO(r.DO.Order(conds...))
}

func (r refKonversiIq105Do) Distinct(cols ...field.Expr) *refKonversiIq105Do {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r refKonversiIq105Do) Omit(cols ...field.Expr) *refKonversiIq105Do {
	return r.withDO(r.DO.Omit(cols...))
}

func (r refKonversiIq105Do) Join(table schema.Tabler, on ...field.Expr) *refKonversiIq105Do {
	return r.withDO(r.DO.Join(table, on...))
}

func (r refKonversiIq105Do) LeftJoin(table schema.Tabler, on ...field.Expr) *refKonversiIq105Do {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r refKonversiIq105Do) RightJoin(table schema.Tabler, on ...field.Expr) *refKonversiIq105Do {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r refKonversiIq105Do) Group(cols ...field.Expr) *refKonversiIq105Do {
	return r.withDO(r.DO.Group(cols...))
}

func (r refKonversiIq105Do) Having(conds ...gen.Condition) *refKonversiIq105Do {
	return r.withDO(r.DO.Having(conds...))
}

func (r refKonversiIq105Do) Limit(limit int) *refKonversiIq105Do {
	return r.withDO(r.DO.Limit(limit))
}

func (r refKonversiIq105Do) Offset(offset int) *refKonversiIq105Do {
	return r.withDO(r.DO.Offset(offset))
}

func (r refKonversiIq105Do) Scopes(funcs ...func(gen.Dao) gen.Dao) *refKonversiIq105Do {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r refKonversiIq105Do) Unscoped() *refKonversiIq105Do {
	return r.withDO(r.DO.Unscoped())
}

func (r refKonversiIq105Do) Create(values ...*entity.RefKonversiIq105) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r refKonversiIq105Do) CreateInBatches(values []*entity.RefKonversiIq105, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r refKonversiIq105Do) Save(values ...*entity.RefKonversiIq105) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r refKonversiIq105Do) First() (*entity.RefKonversiIq105, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefKonversiIq105), nil
	}
}

func (r refKonversiIq105Do) Take() (*entity.RefKonversiIq105, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefKonversiIq105), nil
	}
}

func (r refKonversiIq105Do) Last() (*entity.RefKonversiIq105, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefKonversiIq105), nil
	}
}

func (r refKonversiIq105Do) Find() ([]*entity.RefKonversiIq105, error) {
	result, err := r.DO.Find()
	return result.([]*entity.RefKonversiIq105), err
}

func (r refKonversiIq105Do) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RefKonversiIq105, err error) {
	buf := make([]*entity.RefKonversiIq105, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r refKonversiIq105Do) FindInBatches(result *[]*entity.RefKonversiIq105, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r refKonversiIq105Do) Attrs(attrs ...field.AssignExpr) *refKonversiIq105Do {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r refKonversiIq105Do) Assign(attrs ...field.AssignExpr) *refKonversiIq105Do {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r refKonversiIq105Do) Joins(fields ...field.RelationField) *refKonversiIq105Do {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r refKonversiIq105Do) Preload(fields ...field.RelationField) *refKonversiIq105Do {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r refKonversiIq105Do) FirstOrInit() (*entity.RefKonversiIq105, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefKonversiIq105), nil
	}
}

func (r refKonversiIq105Do) FirstOrCreate() (*entity.RefKonversiIq105, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefKonversiIq105), nil
	}
}

func (r refKonversiIq105Do) FindByPage(offset int, limit int) (result []*entity.RefKonversiIq105, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r refKonversiIq105Do) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r refKonversiIq105Do) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r refKonversiIq105Do) Delete(models ...*entity.RefKonversiIq105) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *refKonversiIq105Do) withDO(do gen.Dao) *refKonversiIq105Do {
	r.DO = *do.(*gen.DO)
	return r
}
