// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package export

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"irwanka/sicerdas/utils/gen-model/entity"
)

func newRefModelKesehatanMental(db *gorm.DB, opts ...gen.DOOption) refModelKesehatanMental {
	_refModelKesehatanMental := refModelKesehatanMental{}

	_refModelKesehatanMental.refModelKesehatanMentalDo.UseDB(db, opts...)
	_refModelKesehatanMental.refModelKesehatanMentalDo.UseModel(&entity.RefModelKesehatanMental{})

	tableName := _refModelKesehatanMental.refModelKesehatanMentalDo.TableName()
	_refModelKesehatanMental.ALL = field.NewAsterisk(tableName)
	_refModelKesehatanMental.ID = field.NewInt32(tableName, "id")
	_refModelKesehatanMental.Nama = field.NewString(tableName, "nama")

	_refModelKesehatanMental.fillFieldMap()

	return _refModelKesehatanMental
}

type refModelKesehatanMental struct {
	refModelKesehatanMentalDo refModelKesehatanMentalDo

	ALL  field.Asterisk
	ID   field.Int32
	Nama field.String

	fieldMap map[string]field.Expr
}

func (r refModelKesehatanMental) Table(newTableName string) *refModelKesehatanMental {
	r.refModelKesehatanMentalDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r refModelKesehatanMental) As(alias string) *refModelKesehatanMental {
	r.refModelKesehatanMentalDo.DO = *(r.refModelKesehatanMentalDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *refModelKesehatanMental) updateTableName(table string) *refModelKesehatanMental {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt32(table, "id")
	r.Nama = field.NewString(table, "nama")

	r.fillFieldMap()

	return r
}

func (r *refModelKesehatanMental) WithContext(ctx context.Context) *refModelKesehatanMentalDo {
	return r.refModelKesehatanMentalDo.WithContext(ctx)
}

func (r refModelKesehatanMental) TableName() string { return r.refModelKesehatanMentalDo.TableName() }

func (r refModelKesehatanMental) Alias() string { return r.refModelKesehatanMentalDo.Alias() }

func (r refModelKesehatanMental) Columns(cols ...field.Expr) gen.Columns {
	return r.refModelKesehatanMentalDo.Columns(cols...)
}

func (r *refModelKesehatanMental) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *refModelKesehatanMental) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 2)
	r.fieldMap["id"] = r.ID
	r.fieldMap["nama"] = r.Nama
}

func (r refModelKesehatanMental) clone(db *gorm.DB) refModelKesehatanMental {
	r.refModelKesehatanMentalDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r refModelKesehatanMental) replaceDB(db *gorm.DB) refModelKesehatanMental {
	r.refModelKesehatanMentalDo.ReplaceDB(db)
	return r
}

type refModelKesehatanMentalDo struct{ gen.DO }

func (r refModelKesehatanMentalDo) Debug() *refModelKesehatanMentalDo {
	return r.withDO(r.DO.Debug())
}

func (r refModelKesehatanMentalDo) WithContext(ctx context.Context) *refModelKesehatanMentalDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r refModelKesehatanMentalDo) ReadDB() *refModelKesehatanMentalDo {
	return r.Clauses(dbresolver.Read)
}

func (r refModelKesehatanMentalDo) WriteDB() *refModelKesehatanMentalDo {
	return r.Clauses(dbresolver.Write)
}

func (r refModelKesehatanMentalDo) Session(config *gorm.Session) *refModelKesehatanMentalDo {
	return r.withDO(r.DO.Session(config))
}

func (r refModelKesehatanMentalDo) Clauses(conds ...clause.Expression) *refModelKesehatanMentalDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r refModelKesehatanMentalDo) Returning(value interface{}, columns ...string) *refModelKesehatanMentalDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r refModelKesehatanMentalDo) Not(conds ...gen.Condition) *refModelKesehatanMentalDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r refModelKesehatanMentalDo) Or(conds ...gen.Condition) *refModelKesehatanMentalDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r refModelKesehatanMentalDo) Select(conds ...field.Expr) *refModelKesehatanMentalDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r refModelKesehatanMentalDo) Where(conds ...gen.Condition) *refModelKesehatanMentalDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r refModelKesehatanMentalDo) Order(conds ...field.Expr) *refModelKesehatanMentalDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r refModelKesehatanMentalDo) Distinct(cols ...field.Expr) *refModelKesehatanMentalDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r refModelKesehatanMentalDo) Omit(cols ...field.Expr) *refModelKesehatanMentalDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r refModelKesehatanMentalDo) Join(table schema.Tabler, on ...field.Expr) *refModelKesehatanMentalDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r refModelKesehatanMentalDo) LeftJoin(table schema.Tabler, on ...field.Expr) *refModelKesehatanMentalDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r refModelKesehatanMentalDo) RightJoin(table schema.Tabler, on ...field.Expr) *refModelKesehatanMentalDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r refModelKesehatanMentalDo) Group(cols ...field.Expr) *refModelKesehatanMentalDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r refModelKesehatanMentalDo) Having(conds ...gen.Condition) *refModelKesehatanMentalDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r refModelKesehatanMentalDo) Limit(limit int) *refModelKesehatanMentalDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r refModelKesehatanMentalDo) Offset(offset int) *refModelKesehatanMentalDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r refModelKesehatanMentalDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *refModelKesehatanMentalDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r refModelKesehatanMentalDo) Unscoped() *refModelKesehatanMentalDo {
	return r.withDO(r.DO.Unscoped())
}

func (r refModelKesehatanMentalDo) Create(values ...*entity.RefModelKesehatanMental) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r refModelKesehatanMentalDo) CreateInBatches(values []*entity.RefModelKesehatanMental, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r refModelKesehatanMentalDo) Save(values ...*entity.RefModelKesehatanMental) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r refModelKesehatanMentalDo) First() (*entity.RefModelKesehatanMental, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefModelKesehatanMental), nil
	}
}

func (r refModelKesehatanMentalDo) Take() (*entity.RefModelKesehatanMental, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefModelKesehatanMental), nil
	}
}

func (r refModelKesehatanMentalDo) Last() (*entity.RefModelKesehatanMental, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefModelKesehatanMental), nil
	}
}

func (r refModelKesehatanMentalDo) Find() ([]*entity.RefModelKesehatanMental, error) {
	result, err := r.DO.Find()
	return result.([]*entity.RefModelKesehatanMental), err
}

func (r refModelKesehatanMentalDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RefModelKesehatanMental, err error) {
	buf := make([]*entity.RefModelKesehatanMental, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r refModelKesehatanMentalDo) FindInBatches(result *[]*entity.RefModelKesehatanMental, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r refModelKesehatanMentalDo) Attrs(attrs ...field.AssignExpr) *refModelKesehatanMentalDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r refModelKesehatanMentalDo) Assign(attrs ...field.AssignExpr) *refModelKesehatanMentalDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r refModelKesehatanMentalDo) Joins(fields ...field.RelationField) *refModelKesehatanMentalDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r refModelKesehatanMentalDo) Preload(fields ...field.RelationField) *refModelKesehatanMentalDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r refModelKesehatanMentalDo) FirstOrInit() (*entity.RefModelKesehatanMental, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefModelKesehatanMental), nil
	}
}

func (r refModelKesehatanMentalDo) FirstOrCreate() (*entity.RefModelKesehatanMental, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefModelKesehatanMental), nil
	}
}

func (r refModelKesehatanMentalDo) FindByPage(offset int, limit int) (result []*entity.RefModelKesehatanMental, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r refModelKesehatanMentalDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r refModelKesehatanMentalDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r refModelKesehatanMentalDo) Delete(models ...*entity.RefModelKesehatanMental) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *refModelKesehatanMentalDo) withDO(do gen.Dao) *refModelKesehatanMentalDo {
	r.DO = *do.(*gen.DO)
	return r
}
