// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package export

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"irwanka/sicerdas/utils/gen-model/entity"
)

func newRefKomponenKepribadianManajerial(db *gorm.DB, opts ...gen.DOOption) refKomponenKepribadianManajerial {
	_refKomponenKepribadianManajerial := refKomponenKepribadianManajerial{}

	_refKomponenKepribadianManajerial.refKomponenKepribadianManajerialDo.UseDB(db, opts...)
	_refKomponenKepribadianManajerial.refKomponenKepribadianManajerialDo.UseModel(&entity.RefKomponenKepribadianManajerial{})

	tableName := _refKomponenKepribadianManajerial.refKomponenKepribadianManajerialDo.TableName()
	_refKomponenKepribadianManajerial.ALL = field.NewAsterisk(tableName)
	_refKomponenKepribadianManajerial.ID = field.NewInt32(tableName, "id")
	_refKomponenKepribadianManajerial.Komponen = field.NewString(tableName, "komponen")
	_refKomponenKepribadianManajerial.Deskripsi = field.NewString(tableName, "deskripsi")
	_refKomponenKepribadianManajerial.FieldSkoring = field.NewString(tableName, "field_skoring")
	_refKomponenKepribadianManajerial.Icon = field.NewString(tableName, "icon")

	_refKomponenKepribadianManajerial.fillFieldMap()

	return _refKomponenKepribadianManajerial
}

type refKomponenKepribadianManajerial struct {
	refKomponenKepribadianManajerialDo refKomponenKepribadianManajerialDo

	ALL          field.Asterisk
	ID           field.Int32
	Komponen     field.String
	Deskripsi    field.String
	FieldSkoring field.String
	Icon         field.String

	fieldMap map[string]field.Expr
}

func (r refKomponenKepribadianManajerial) Table(newTableName string) *refKomponenKepribadianManajerial {
	r.refKomponenKepribadianManajerialDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r refKomponenKepribadianManajerial) As(alias string) *refKomponenKepribadianManajerial {
	r.refKomponenKepribadianManajerialDo.DO = *(r.refKomponenKepribadianManajerialDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *refKomponenKepribadianManajerial) updateTableName(table string) *refKomponenKepribadianManajerial {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt32(table, "id")
	r.Komponen = field.NewString(table, "komponen")
	r.Deskripsi = field.NewString(table, "deskripsi")
	r.FieldSkoring = field.NewString(table, "field_skoring")
	r.Icon = field.NewString(table, "icon")

	r.fillFieldMap()

	return r
}

func (r *refKomponenKepribadianManajerial) WithContext(ctx context.Context) *refKomponenKepribadianManajerialDo {
	return r.refKomponenKepribadianManajerialDo.WithContext(ctx)
}

func (r refKomponenKepribadianManajerial) TableName() string {
	return r.refKomponenKepribadianManajerialDo.TableName()
}

func (r refKomponenKepribadianManajerial) Alias() string {
	return r.refKomponenKepribadianManajerialDo.Alias()
}

func (r refKomponenKepribadianManajerial) Columns(cols ...field.Expr) gen.Columns {
	return r.refKomponenKepribadianManajerialDo.Columns(cols...)
}

func (r *refKomponenKepribadianManajerial) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *refKomponenKepribadianManajerial) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 5)
	r.fieldMap["id"] = r.ID
	r.fieldMap["komponen"] = r.Komponen
	r.fieldMap["deskripsi"] = r.Deskripsi
	r.fieldMap["field_skoring"] = r.FieldSkoring
	r.fieldMap["icon"] = r.Icon
}

func (r refKomponenKepribadianManajerial) clone(db *gorm.DB) refKomponenKepribadianManajerial {
	r.refKomponenKepribadianManajerialDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r refKomponenKepribadianManajerial) replaceDB(db *gorm.DB) refKomponenKepribadianManajerial {
	r.refKomponenKepribadianManajerialDo.ReplaceDB(db)
	return r
}

type refKomponenKepribadianManajerialDo struct{ gen.DO }

func (r refKomponenKepribadianManajerialDo) Debug() *refKomponenKepribadianManajerialDo {
	return r.withDO(r.DO.Debug())
}

func (r refKomponenKepribadianManajerialDo) WithContext(ctx context.Context) *refKomponenKepribadianManajerialDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r refKomponenKepribadianManajerialDo) ReadDB() *refKomponenKepribadianManajerialDo {
	return r.Clauses(dbresolver.Read)
}

func (r refKomponenKepribadianManajerialDo) WriteDB() *refKomponenKepribadianManajerialDo {
	return r.Clauses(dbresolver.Write)
}

func (r refKomponenKepribadianManajerialDo) Session(config *gorm.Session) *refKomponenKepribadianManajerialDo {
	return r.withDO(r.DO.Session(config))
}

func (r refKomponenKepribadianManajerialDo) Clauses(conds ...clause.Expression) *refKomponenKepribadianManajerialDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r refKomponenKepribadianManajerialDo) Returning(value interface{}, columns ...string) *refKomponenKepribadianManajerialDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r refKomponenKepribadianManajerialDo) Not(conds ...gen.Condition) *refKomponenKepribadianManajerialDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r refKomponenKepribadianManajerialDo) Or(conds ...gen.Condition) *refKomponenKepribadianManajerialDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r refKomponenKepribadianManajerialDo) Select(conds ...field.Expr) *refKomponenKepribadianManajerialDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r refKomponenKepribadianManajerialDo) Where(conds ...gen.Condition) *refKomponenKepribadianManajerialDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r refKomponenKepribadianManajerialDo) Order(conds ...field.Expr) *refKomponenKepribadianManajerialDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r refKomponenKepribadianManajerialDo) Distinct(cols ...field.Expr) *refKomponenKepribadianManajerialDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r refKomponenKepribadianManajerialDo) Omit(cols ...field.Expr) *refKomponenKepribadianManajerialDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r refKomponenKepribadianManajerialDo) Join(table schema.Tabler, on ...field.Expr) *refKomponenKepribadianManajerialDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r refKomponenKepribadianManajerialDo) LeftJoin(table schema.Tabler, on ...field.Expr) *refKomponenKepribadianManajerialDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r refKomponenKepribadianManajerialDo) RightJoin(table schema.Tabler, on ...field.Expr) *refKomponenKepribadianManajerialDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r refKomponenKepribadianManajerialDo) Group(cols ...field.Expr) *refKomponenKepribadianManajerialDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r refKomponenKepribadianManajerialDo) Having(conds ...gen.Condition) *refKomponenKepribadianManajerialDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r refKomponenKepribadianManajerialDo) Limit(limit int) *refKomponenKepribadianManajerialDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r refKomponenKepribadianManajerialDo) Offset(offset int) *refKomponenKepribadianManajerialDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r refKomponenKepribadianManajerialDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *refKomponenKepribadianManajerialDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r refKomponenKepribadianManajerialDo) Unscoped() *refKomponenKepribadianManajerialDo {
	return r.withDO(r.DO.Unscoped())
}

func (r refKomponenKepribadianManajerialDo) Create(values ...*entity.RefKomponenKepribadianManajerial) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r refKomponenKepribadianManajerialDo) CreateInBatches(values []*entity.RefKomponenKepribadianManajerial, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r refKomponenKepribadianManajerialDo) Save(values ...*entity.RefKomponenKepribadianManajerial) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r refKomponenKepribadianManajerialDo) First() (*entity.RefKomponenKepribadianManajerial, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefKomponenKepribadianManajerial), nil
	}
}

func (r refKomponenKepribadianManajerialDo) Take() (*entity.RefKomponenKepribadianManajerial, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefKomponenKepribadianManajerial), nil
	}
}

func (r refKomponenKepribadianManajerialDo) Last() (*entity.RefKomponenKepribadianManajerial, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefKomponenKepribadianManajerial), nil
	}
}

func (r refKomponenKepribadianManajerialDo) Find() ([]*entity.RefKomponenKepribadianManajerial, error) {
	result, err := r.DO.Find()
	return result.([]*entity.RefKomponenKepribadianManajerial), err
}

func (r refKomponenKepribadianManajerialDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RefKomponenKepribadianManajerial, err error) {
	buf := make([]*entity.RefKomponenKepribadianManajerial, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r refKomponenKepribadianManajerialDo) FindInBatches(result *[]*entity.RefKomponenKepribadianManajerial, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r refKomponenKepribadianManajerialDo) Attrs(attrs ...field.AssignExpr) *refKomponenKepribadianManajerialDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r refKomponenKepribadianManajerialDo) Assign(attrs ...field.AssignExpr) *refKomponenKepribadianManajerialDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r refKomponenKepribadianManajerialDo) Joins(fields ...field.RelationField) *refKomponenKepribadianManajerialDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r refKomponenKepribadianManajerialDo) Preload(fields ...field.RelationField) *refKomponenKepribadianManajerialDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r refKomponenKepribadianManajerialDo) FirstOrInit() (*entity.RefKomponenKepribadianManajerial, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefKomponenKepribadianManajerial), nil
	}
}

func (r refKomponenKepribadianManajerialDo) FirstOrCreate() (*entity.RefKomponenKepribadianManajerial, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefKomponenKepribadianManajerial), nil
	}
}

func (r refKomponenKepribadianManajerialDo) FindByPage(offset int, limit int) (result []*entity.RefKomponenKepribadianManajerial, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r refKomponenKepribadianManajerialDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r refKomponenKepribadianManajerialDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r refKomponenKepribadianManajerialDo) Delete(models ...*entity.RefKomponenKepribadianManajerial) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *refKomponenKepribadianManajerialDo) withDO(do gen.Dao) *refKomponenKepribadianManajerialDo {
	r.DO = *do.(*gen.DO)
	return r
}
