// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package export

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"irwanka/sicerdas/utils/gen-model/entity"
)

func newRefKonversiIq(db *gorm.DB, opts ...gen.DOOption) refKonversiIq {
	_refKonversiIq := refKonversiIq{}

	_refKonversiIq.refKonversiIqDo.UseDB(db, opts...)
	_refKonversiIq.refKonversiIqDo.UseModel(&entity.RefKonversiIq{})

	tableName := _refKonversiIq.refKonversiIqDo.TableName()
	_refKonversiIq.ALL = field.NewAsterisk(tableName)
	_refKonversiIq.ID = field.NewInt32(tableName, "id")
	_refKonversiIq.SkorX = field.NewInt32(tableName, "skor_x")
	_refKonversiIq.TotIq = field.NewFloat32(tableName, "tot_iq")
	_refKonversiIq.Klasifikasi = field.NewString(tableName, "klasifikasi")

	_refKonversiIq.fillFieldMap()

	return _refKonversiIq
}

type refKonversiIq struct {
	refKonversiIqDo refKonversiIqDo

	ALL         field.Asterisk
	ID          field.Int32
	SkorX       field.Int32
	TotIq       field.Float32
	Klasifikasi field.String

	fieldMap map[string]field.Expr
}

func (r refKonversiIq) Table(newTableName string) *refKonversiIq {
	r.refKonversiIqDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r refKonversiIq) As(alias string) *refKonversiIq {
	r.refKonversiIqDo.DO = *(r.refKonversiIqDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *refKonversiIq) updateTableName(table string) *refKonversiIq {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt32(table, "id")
	r.SkorX = field.NewInt32(table, "skor_x")
	r.TotIq = field.NewFloat32(table, "tot_iq")
	r.Klasifikasi = field.NewString(table, "klasifikasi")

	r.fillFieldMap()

	return r
}

func (r *refKonversiIq) WithContext(ctx context.Context) *refKonversiIqDo {
	return r.refKonversiIqDo.WithContext(ctx)
}

func (r refKonversiIq) TableName() string { return r.refKonversiIqDo.TableName() }

func (r refKonversiIq) Alias() string { return r.refKonversiIqDo.Alias() }

func (r refKonversiIq) Columns(cols ...field.Expr) gen.Columns {
	return r.refKonversiIqDo.Columns(cols...)
}

func (r *refKonversiIq) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *refKonversiIq) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 4)
	r.fieldMap["id"] = r.ID
	r.fieldMap["skor_x"] = r.SkorX
	r.fieldMap["tot_iq"] = r.TotIq
	r.fieldMap["klasifikasi"] = r.Klasifikasi
}

func (r refKonversiIq) clone(db *gorm.DB) refKonversiIq {
	r.refKonversiIqDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r refKonversiIq) replaceDB(db *gorm.DB) refKonversiIq {
	r.refKonversiIqDo.ReplaceDB(db)
	return r
}

type refKonversiIqDo struct{ gen.DO }

func (r refKonversiIqDo) Debug() *refKonversiIqDo {
	return r.withDO(r.DO.Debug())
}

func (r refKonversiIqDo) WithContext(ctx context.Context) *refKonversiIqDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r refKonversiIqDo) ReadDB() *refKonversiIqDo {
	return r.Clauses(dbresolver.Read)
}

func (r refKonversiIqDo) WriteDB() *refKonversiIqDo {
	return r.Clauses(dbresolver.Write)
}

func (r refKonversiIqDo) Session(config *gorm.Session) *refKonversiIqDo {
	return r.withDO(r.DO.Session(config))
}

func (r refKonversiIqDo) Clauses(conds ...clause.Expression) *refKonversiIqDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r refKonversiIqDo) Returning(value interface{}, columns ...string) *refKonversiIqDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r refKonversiIqDo) Not(conds ...gen.Condition) *refKonversiIqDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r refKonversiIqDo) Or(conds ...gen.Condition) *refKonversiIqDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r refKonversiIqDo) Select(conds ...field.Expr) *refKonversiIqDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r refKonversiIqDo) Where(conds ...gen.Condition) *refKonversiIqDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r refKonversiIqDo) Order(conds ...field.Expr) *refKonversiIqDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r refKonversiIqDo) Distinct(cols ...field.Expr) *refKonversiIqDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r refKonversiIqDo) Omit(cols ...field.Expr) *refKonversiIqDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r refKonversiIqDo) Join(table schema.Tabler, on ...field.Expr) *refKonversiIqDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r refKonversiIqDo) LeftJoin(table schema.Tabler, on ...field.Expr) *refKonversiIqDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r refKonversiIqDo) RightJoin(table schema.Tabler, on ...field.Expr) *refKonversiIqDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r refKonversiIqDo) Group(cols ...field.Expr) *refKonversiIqDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r refKonversiIqDo) Having(conds ...gen.Condition) *refKonversiIqDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r refKonversiIqDo) Limit(limit int) *refKonversiIqDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r refKonversiIqDo) Offset(offset int) *refKonversiIqDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r refKonversiIqDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *refKonversiIqDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r refKonversiIqDo) Unscoped() *refKonversiIqDo {
	return r.withDO(r.DO.Unscoped())
}

func (r refKonversiIqDo) Create(values ...*entity.RefKonversiIq) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r refKonversiIqDo) CreateInBatches(values []*entity.RefKonversiIq, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r refKonversiIqDo) Save(values ...*entity.RefKonversiIq) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r refKonversiIqDo) First() (*entity.RefKonversiIq, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefKonversiIq), nil
	}
}

func (r refKonversiIqDo) Take() (*entity.RefKonversiIq, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefKonversiIq), nil
	}
}

func (r refKonversiIqDo) Last() (*entity.RefKonversiIq, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefKonversiIq), nil
	}
}

func (r refKonversiIqDo) Find() ([]*entity.RefKonversiIq, error) {
	result, err := r.DO.Find()
	return result.([]*entity.RefKonversiIq), err
}

func (r refKonversiIqDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RefKonversiIq, err error) {
	buf := make([]*entity.RefKonversiIq, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r refKonversiIqDo) FindInBatches(result *[]*entity.RefKonversiIq, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r refKonversiIqDo) Attrs(attrs ...field.AssignExpr) *refKonversiIqDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r refKonversiIqDo) Assign(attrs ...field.AssignExpr) *refKonversiIqDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r refKonversiIqDo) Joins(fields ...field.RelationField) *refKonversiIqDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r refKonversiIqDo) Preload(fields ...field.RelationField) *refKonversiIqDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r refKonversiIqDo) FirstOrInit() (*entity.RefKonversiIq, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefKonversiIq), nil
	}
}

func (r refKonversiIqDo) FirstOrCreate() (*entity.RefKonversiIq, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefKonversiIq), nil
	}
}

func (r refKonversiIqDo) FindByPage(offset int, limit int) (result []*entity.RefKonversiIq, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r refKonversiIqDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r refKonversiIqDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r refKonversiIqDo) Delete(models ...*entity.RefKonversiIq) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *refKonversiIqDo) withDO(do gen.Dao) *refKonversiIqDo {
	r.DO = *do.(*gen.DO)
	return r
}
