// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package export

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"irwanka/sicerdas/utils/gen-model/entity"
)

func newRefRekomendasiAkhirPeminatanSma(db *gorm.DB, opts ...gen.DOOption) refRekomendasiAkhirPeminatanSma {
	_refRekomendasiAkhirPeminatanSma := refRekomendasiAkhirPeminatanSma{}

	_refRekomendasiAkhirPeminatanSma.refRekomendasiAkhirPeminatanSmaDo.UseDB(db, opts...)
	_refRekomendasiAkhirPeminatanSma.refRekomendasiAkhirPeminatanSmaDo.UseModel(&entity.RefRekomendasiAkhirPeminatanSma{})

	tableName := _refRekomendasiAkhirPeminatanSma.refRekomendasiAkhirPeminatanSmaDo.TableName()
	_refRekomendasiAkhirPeminatanSma.ALL = field.NewAsterisk(tableName)
	_refRekomendasiAkhirPeminatanSma.ID = field.NewInt32(tableName, "id")
	_refRekomendasiAkhirPeminatanSma.RekomMinat = field.NewString(tableName, "rekom_minat")
	_refRekomendasiAkhirPeminatanSma.RekomSikapPelajaran = field.NewString(tableName, "rekom_sikap_pelajaran")
	_refRekomendasiAkhirPeminatanSma.RekomAkhir = field.NewString(tableName, "rekom_akhir")

	_refRekomendasiAkhirPeminatanSma.fillFieldMap()

	return _refRekomendasiAkhirPeminatanSma
}

type refRekomendasiAkhirPeminatanSma struct {
	refRekomendasiAkhirPeminatanSmaDo refRekomendasiAkhirPeminatanSmaDo

	ALL                 field.Asterisk
	ID                  field.Int32
	RekomMinat          field.String
	RekomSikapPelajaran field.String
	RekomAkhir          field.String

	fieldMap map[string]field.Expr
}

func (r refRekomendasiAkhirPeminatanSma) Table(newTableName string) *refRekomendasiAkhirPeminatanSma {
	r.refRekomendasiAkhirPeminatanSmaDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r refRekomendasiAkhirPeminatanSma) As(alias string) *refRekomendasiAkhirPeminatanSma {
	r.refRekomendasiAkhirPeminatanSmaDo.DO = *(r.refRekomendasiAkhirPeminatanSmaDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *refRekomendasiAkhirPeminatanSma) updateTableName(table string) *refRekomendasiAkhirPeminatanSma {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt32(table, "id")
	r.RekomMinat = field.NewString(table, "rekom_minat")
	r.RekomSikapPelajaran = field.NewString(table, "rekom_sikap_pelajaran")
	r.RekomAkhir = field.NewString(table, "rekom_akhir")

	r.fillFieldMap()

	return r
}

func (r *refRekomendasiAkhirPeminatanSma) WithContext(ctx context.Context) *refRekomendasiAkhirPeminatanSmaDo {
	return r.refRekomendasiAkhirPeminatanSmaDo.WithContext(ctx)
}

func (r refRekomendasiAkhirPeminatanSma) TableName() string {
	return r.refRekomendasiAkhirPeminatanSmaDo.TableName()
}

func (r refRekomendasiAkhirPeminatanSma) Alias() string {
	return r.refRekomendasiAkhirPeminatanSmaDo.Alias()
}

func (r refRekomendasiAkhirPeminatanSma) Columns(cols ...field.Expr) gen.Columns {
	return r.refRekomendasiAkhirPeminatanSmaDo.Columns(cols...)
}

func (r *refRekomendasiAkhirPeminatanSma) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *refRekomendasiAkhirPeminatanSma) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 4)
	r.fieldMap["id"] = r.ID
	r.fieldMap["rekom_minat"] = r.RekomMinat
	r.fieldMap["rekom_sikap_pelajaran"] = r.RekomSikapPelajaran
	r.fieldMap["rekom_akhir"] = r.RekomAkhir
}

func (r refRekomendasiAkhirPeminatanSma) clone(db *gorm.DB) refRekomendasiAkhirPeminatanSma {
	r.refRekomendasiAkhirPeminatanSmaDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r refRekomendasiAkhirPeminatanSma) replaceDB(db *gorm.DB) refRekomendasiAkhirPeminatanSma {
	r.refRekomendasiAkhirPeminatanSmaDo.ReplaceDB(db)
	return r
}

type refRekomendasiAkhirPeminatanSmaDo struct{ gen.DO }

func (r refRekomendasiAkhirPeminatanSmaDo) Debug() *refRekomendasiAkhirPeminatanSmaDo {
	return r.withDO(r.DO.Debug())
}

func (r refRekomendasiAkhirPeminatanSmaDo) WithContext(ctx context.Context) *refRekomendasiAkhirPeminatanSmaDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r refRekomendasiAkhirPeminatanSmaDo) ReadDB() *refRekomendasiAkhirPeminatanSmaDo {
	return r.Clauses(dbresolver.Read)
}

func (r refRekomendasiAkhirPeminatanSmaDo) WriteDB() *refRekomendasiAkhirPeminatanSmaDo {
	return r.Clauses(dbresolver.Write)
}

func (r refRekomendasiAkhirPeminatanSmaDo) Session(config *gorm.Session) *refRekomendasiAkhirPeminatanSmaDo {
	return r.withDO(r.DO.Session(config))
}

func (r refRekomendasiAkhirPeminatanSmaDo) Clauses(conds ...clause.Expression) *refRekomendasiAkhirPeminatanSmaDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r refRekomendasiAkhirPeminatanSmaDo) Returning(value interface{}, columns ...string) *refRekomendasiAkhirPeminatanSmaDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r refRekomendasiAkhirPeminatanSmaDo) Not(conds ...gen.Condition) *refRekomendasiAkhirPeminatanSmaDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r refRekomendasiAkhirPeminatanSmaDo) Or(conds ...gen.Condition) *refRekomendasiAkhirPeminatanSmaDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r refRekomendasiAkhirPeminatanSmaDo) Select(conds ...field.Expr) *refRekomendasiAkhirPeminatanSmaDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r refRekomendasiAkhirPeminatanSmaDo) Where(conds ...gen.Condition) *refRekomendasiAkhirPeminatanSmaDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r refRekomendasiAkhirPeminatanSmaDo) Order(conds ...field.Expr) *refRekomendasiAkhirPeminatanSmaDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r refRekomendasiAkhirPeminatanSmaDo) Distinct(cols ...field.Expr) *refRekomendasiAkhirPeminatanSmaDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r refRekomendasiAkhirPeminatanSmaDo) Omit(cols ...field.Expr) *refRekomendasiAkhirPeminatanSmaDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r refRekomendasiAkhirPeminatanSmaDo) Join(table schema.Tabler, on ...field.Expr) *refRekomendasiAkhirPeminatanSmaDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r refRekomendasiAkhirPeminatanSmaDo) LeftJoin(table schema.Tabler, on ...field.Expr) *refRekomendasiAkhirPeminatanSmaDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r refRekomendasiAkhirPeminatanSmaDo) RightJoin(table schema.Tabler, on ...field.Expr) *refRekomendasiAkhirPeminatanSmaDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r refRekomendasiAkhirPeminatanSmaDo) Group(cols ...field.Expr) *refRekomendasiAkhirPeminatanSmaDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r refRekomendasiAkhirPeminatanSmaDo) Having(conds ...gen.Condition) *refRekomendasiAkhirPeminatanSmaDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r refRekomendasiAkhirPeminatanSmaDo) Limit(limit int) *refRekomendasiAkhirPeminatanSmaDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r refRekomendasiAkhirPeminatanSmaDo) Offset(offset int) *refRekomendasiAkhirPeminatanSmaDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r refRekomendasiAkhirPeminatanSmaDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *refRekomendasiAkhirPeminatanSmaDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r refRekomendasiAkhirPeminatanSmaDo) Unscoped() *refRekomendasiAkhirPeminatanSmaDo {
	return r.withDO(r.DO.Unscoped())
}

func (r refRekomendasiAkhirPeminatanSmaDo) Create(values ...*entity.RefRekomendasiAkhirPeminatanSma) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r refRekomendasiAkhirPeminatanSmaDo) CreateInBatches(values []*entity.RefRekomendasiAkhirPeminatanSma, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r refRekomendasiAkhirPeminatanSmaDo) Save(values ...*entity.RefRekomendasiAkhirPeminatanSma) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r refRekomendasiAkhirPeminatanSmaDo) First() (*entity.RefRekomendasiAkhirPeminatanSma, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefRekomendasiAkhirPeminatanSma), nil
	}
}

func (r refRekomendasiAkhirPeminatanSmaDo) Take() (*entity.RefRekomendasiAkhirPeminatanSma, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefRekomendasiAkhirPeminatanSma), nil
	}
}

func (r refRekomendasiAkhirPeminatanSmaDo) Last() (*entity.RefRekomendasiAkhirPeminatanSma, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefRekomendasiAkhirPeminatanSma), nil
	}
}

func (r refRekomendasiAkhirPeminatanSmaDo) Find() ([]*entity.RefRekomendasiAkhirPeminatanSma, error) {
	result, err := r.DO.Find()
	return result.([]*entity.RefRekomendasiAkhirPeminatanSma), err
}

func (r refRekomendasiAkhirPeminatanSmaDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RefRekomendasiAkhirPeminatanSma, err error) {
	buf := make([]*entity.RefRekomendasiAkhirPeminatanSma, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r refRekomendasiAkhirPeminatanSmaDo) FindInBatches(result *[]*entity.RefRekomendasiAkhirPeminatanSma, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r refRekomendasiAkhirPeminatanSmaDo) Attrs(attrs ...field.AssignExpr) *refRekomendasiAkhirPeminatanSmaDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r refRekomendasiAkhirPeminatanSmaDo) Assign(attrs ...field.AssignExpr) *refRekomendasiAkhirPeminatanSmaDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r refRekomendasiAkhirPeminatanSmaDo) Joins(fields ...field.RelationField) *refRekomendasiAkhirPeminatanSmaDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r refRekomendasiAkhirPeminatanSmaDo) Preload(fields ...field.RelationField) *refRekomendasiAkhirPeminatanSmaDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r refRekomendasiAkhirPeminatanSmaDo) FirstOrInit() (*entity.RefRekomendasiAkhirPeminatanSma, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefRekomendasiAkhirPeminatanSma), nil
	}
}

func (r refRekomendasiAkhirPeminatanSmaDo) FirstOrCreate() (*entity.RefRekomendasiAkhirPeminatanSma, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefRekomendasiAkhirPeminatanSma), nil
	}
}

func (r refRekomendasiAkhirPeminatanSmaDo) FindByPage(offset int, limit int) (result []*entity.RefRekomendasiAkhirPeminatanSma, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r refRekomendasiAkhirPeminatanSmaDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r refRekomendasiAkhirPeminatanSmaDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r refRekomendasiAkhirPeminatanSmaDo) Delete(models ...*entity.RefRekomendasiAkhirPeminatanSma) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *refRekomendasiAkhirPeminatanSmaDo) withDO(do gen.Dao) *refRekomendasiAkhirPeminatanSmaDo {
	r.DO = *do.(*gen.DO)
	return r
}
