// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package export

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"irwanka/sicerdas/utils/gen-model/entity"
)

func newRefGayaBelajar(db *gorm.DB, opts ...gen.DOOption) refGayaBelajar {
	_refGayaBelajar := refGayaBelajar{}

	_refGayaBelajar.refGayaBelajarDo.UseDB(db, opts...)
	_refGayaBelajar.refGayaBelajarDo.UseModel(&entity.RefGayaBelajar{})

	tableName := _refGayaBelajar.refGayaBelajarDo.TableName()
	_refGayaBelajar.ALL = field.NewAsterisk(tableName)
	_refGayaBelajar.Kode = field.NewString(tableName, "kode")
	_refGayaBelajar.Nama = field.NewString(tableName, "nama")
	_refGayaBelajar.Deskripsi = field.NewString(tableName, "deskripsi")
	_refGayaBelajar.Gambar = field.NewString(tableName, "gambar")

	_refGayaBelajar.fillFieldMap()

	return _refGayaBelajar
}

type refGayaBelajar struct {
	refGayaBelajarDo refGayaBelajarDo

	ALL       field.Asterisk
	Kode      field.String
	Nama      field.String
	Deskripsi field.String
	Gambar    field.String

	fieldMap map[string]field.Expr
}

func (r refGayaBelajar) Table(newTableName string) *refGayaBelajar {
	r.refGayaBelajarDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r refGayaBelajar) As(alias string) *refGayaBelajar {
	r.refGayaBelajarDo.DO = *(r.refGayaBelajarDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *refGayaBelajar) updateTableName(table string) *refGayaBelajar {
	r.ALL = field.NewAsterisk(table)
	r.Kode = field.NewString(table, "kode")
	r.Nama = field.NewString(table, "nama")
	r.Deskripsi = field.NewString(table, "deskripsi")
	r.Gambar = field.NewString(table, "gambar")

	r.fillFieldMap()

	return r
}

func (r *refGayaBelajar) WithContext(ctx context.Context) *refGayaBelajarDo {
	return r.refGayaBelajarDo.WithContext(ctx)
}

func (r refGayaBelajar) TableName() string { return r.refGayaBelajarDo.TableName() }

func (r refGayaBelajar) Alias() string { return r.refGayaBelajarDo.Alias() }

func (r refGayaBelajar) Columns(cols ...field.Expr) gen.Columns {
	return r.refGayaBelajarDo.Columns(cols...)
}

func (r *refGayaBelajar) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *refGayaBelajar) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 4)
	r.fieldMap["kode"] = r.Kode
	r.fieldMap["nama"] = r.Nama
	r.fieldMap["deskripsi"] = r.Deskripsi
	r.fieldMap["gambar"] = r.Gambar
}

func (r refGayaBelajar) clone(db *gorm.DB) refGayaBelajar {
	r.refGayaBelajarDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r refGayaBelajar) replaceDB(db *gorm.DB) refGayaBelajar {
	r.refGayaBelajarDo.ReplaceDB(db)
	return r
}

type refGayaBelajarDo struct{ gen.DO }

func (r refGayaBelajarDo) Debug() *refGayaBelajarDo {
	return r.withDO(r.DO.Debug())
}

func (r refGayaBelajarDo) WithContext(ctx context.Context) *refGayaBelajarDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r refGayaBelajarDo) ReadDB() *refGayaBelajarDo {
	return r.Clauses(dbresolver.Read)
}

func (r refGayaBelajarDo) WriteDB() *refGayaBelajarDo {
	return r.Clauses(dbresolver.Write)
}

func (r refGayaBelajarDo) Session(config *gorm.Session) *refGayaBelajarDo {
	return r.withDO(r.DO.Session(config))
}

func (r refGayaBelajarDo) Clauses(conds ...clause.Expression) *refGayaBelajarDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r refGayaBelajarDo) Returning(value interface{}, columns ...string) *refGayaBelajarDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r refGayaBelajarDo) Not(conds ...gen.Condition) *refGayaBelajarDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r refGayaBelajarDo) Or(conds ...gen.Condition) *refGayaBelajarDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r refGayaBelajarDo) Select(conds ...field.Expr) *refGayaBelajarDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r refGayaBelajarDo) Where(conds ...gen.Condition) *refGayaBelajarDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r refGayaBelajarDo) Order(conds ...field.Expr) *refGayaBelajarDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r refGayaBelajarDo) Distinct(cols ...field.Expr) *refGayaBelajarDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r refGayaBelajarDo) Omit(cols ...field.Expr) *refGayaBelajarDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r refGayaBelajarDo) Join(table schema.Tabler, on ...field.Expr) *refGayaBelajarDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r refGayaBelajarDo) LeftJoin(table schema.Tabler, on ...field.Expr) *refGayaBelajarDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r refGayaBelajarDo) RightJoin(table schema.Tabler, on ...field.Expr) *refGayaBelajarDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r refGayaBelajarDo) Group(cols ...field.Expr) *refGayaBelajarDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r refGayaBelajarDo) Having(conds ...gen.Condition) *refGayaBelajarDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r refGayaBelajarDo) Limit(limit int) *refGayaBelajarDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r refGayaBelajarDo) Offset(offset int) *refGayaBelajarDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r refGayaBelajarDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *refGayaBelajarDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r refGayaBelajarDo) Unscoped() *refGayaBelajarDo {
	return r.withDO(r.DO.Unscoped())
}

func (r refGayaBelajarDo) Create(values ...*entity.RefGayaBelajar) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r refGayaBelajarDo) CreateInBatches(values []*entity.RefGayaBelajar, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r refGayaBelajarDo) Save(values ...*entity.RefGayaBelajar) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r refGayaBelajarDo) First() (*entity.RefGayaBelajar, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefGayaBelajar), nil
	}
}

func (r refGayaBelajarDo) Take() (*entity.RefGayaBelajar, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefGayaBelajar), nil
	}
}

func (r refGayaBelajarDo) Last() (*entity.RefGayaBelajar, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefGayaBelajar), nil
	}
}

func (r refGayaBelajarDo) Find() ([]*entity.RefGayaBelajar, error) {
	result, err := r.DO.Find()
	return result.([]*entity.RefGayaBelajar), err
}

func (r refGayaBelajarDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RefGayaBelajar, err error) {
	buf := make([]*entity.RefGayaBelajar, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r refGayaBelajarDo) FindInBatches(result *[]*entity.RefGayaBelajar, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r refGayaBelajarDo) Attrs(attrs ...field.AssignExpr) *refGayaBelajarDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r refGayaBelajarDo) Assign(attrs ...field.AssignExpr) *refGayaBelajarDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r refGayaBelajarDo) Joins(fields ...field.RelationField) *refGayaBelajarDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r refGayaBelajarDo) Preload(fields ...field.RelationField) *refGayaBelajarDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r refGayaBelajarDo) FirstOrInit() (*entity.RefGayaBelajar, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefGayaBelajar), nil
	}
}

func (r refGayaBelajarDo) FirstOrCreate() (*entity.RefGayaBelajar, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefGayaBelajar), nil
	}
}

func (r refGayaBelajarDo) FindByPage(offset int, limit int) (result []*entity.RefGayaBelajar, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r refGayaBelajarDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r refGayaBelajarDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r refGayaBelajarDo) Delete(models ...*entity.RefGayaBelajar) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *refGayaBelajarDo) withDO(do gen.Dao) *refGayaBelajarDo {
	r.DO = *do.(*gen.DO)
	return r
}
