// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package export

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"irwanka/sicerdas/utils/gen-model/entity"
)

func newRefModelWlb(db *gorm.DB, opts ...gen.DOOption) refModelWlb {
	_refModelWlb := refModelWlb{}

	_refModelWlb.refModelWlbDo.UseDB(db, opts...)
	_refModelWlb.refModelWlbDo.UseModel(&entity.RefModelWlb{})

	tableName := _refModelWlb.refModelWlbDo.TableName()
	_refModelWlb.ALL = field.NewAsterisk(tableName)
	_refModelWlb.ID = field.NewInt32(tableName, "id")
	_refModelWlb.Nama = field.NewString(tableName, "nama")
	_refModelWlb.FieldSkoring = field.NewString(tableName, "field_skoring")

	_refModelWlb.fillFieldMap()

	return _refModelWlb
}

type refModelWlb struct {
	refModelWlbDo refModelWlbDo

	ALL          field.Asterisk
	ID           field.Int32
	Nama         field.String
	FieldSkoring field.String

	fieldMap map[string]field.Expr
}

func (r refModelWlb) Table(newTableName string) *refModelWlb {
	r.refModelWlbDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r refModelWlb) As(alias string) *refModelWlb {
	r.refModelWlbDo.DO = *(r.refModelWlbDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *refModelWlb) updateTableName(table string) *refModelWlb {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt32(table, "id")
	r.Nama = field.NewString(table, "nama")
	r.FieldSkoring = field.NewString(table, "field_skoring")

	r.fillFieldMap()

	return r
}

func (r *refModelWlb) WithContext(ctx context.Context) *refModelWlbDo {
	return r.refModelWlbDo.WithContext(ctx)
}

func (r refModelWlb) TableName() string { return r.refModelWlbDo.TableName() }

func (r refModelWlb) Alias() string { return r.refModelWlbDo.Alias() }

func (r refModelWlb) Columns(cols ...field.Expr) gen.Columns { return r.refModelWlbDo.Columns(cols...) }

func (r *refModelWlb) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *refModelWlb) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 3)
	r.fieldMap["id"] = r.ID
	r.fieldMap["nama"] = r.Nama
	r.fieldMap["field_skoring"] = r.FieldSkoring
}

func (r refModelWlb) clone(db *gorm.DB) refModelWlb {
	r.refModelWlbDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r refModelWlb) replaceDB(db *gorm.DB) refModelWlb {
	r.refModelWlbDo.ReplaceDB(db)
	return r
}

type refModelWlbDo struct{ gen.DO }

func (r refModelWlbDo) Debug() *refModelWlbDo {
	return r.withDO(r.DO.Debug())
}

func (r refModelWlbDo) WithContext(ctx context.Context) *refModelWlbDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r refModelWlbDo) ReadDB() *refModelWlbDo {
	return r.Clauses(dbresolver.Read)
}

func (r refModelWlbDo) WriteDB() *refModelWlbDo {
	return r.Clauses(dbresolver.Write)
}

func (r refModelWlbDo) Session(config *gorm.Session) *refModelWlbDo {
	return r.withDO(r.DO.Session(config))
}

func (r refModelWlbDo) Clauses(conds ...clause.Expression) *refModelWlbDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r refModelWlbDo) Returning(value interface{}, columns ...string) *refModelWlbDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r refModelWlbDo) Not(conds ...gen.Condition) *refModelWlbDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r refModelWlbDo) Or(conds ...gen.Condition) *refModelWlbDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r refModelWlbDo) Select(conds ...field.Expr) *refModelWlbDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r refModelWlbDo) Where(conds ...gen.Condition) *refModelWlbDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r refModelWlbDo) Order(conds ...field.Expr) *refModelWlbDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r refModelWlbDo) Distinct(cols ...field.Expr) *refModelWlbDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r refModelWlbDo) Omit(cols ...field.Expr) *refModelWlbDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r refModelWlbDo) Join(table schema.Tabler, on ...field.Expr) *refModelWlbDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r refModelWlbDo) LeftJoin(table schema.Tabler, on ...field.Expr) *refModelWlbDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r refModelWlbDo) RightJoin(table schema.Tabler, on ...field.Expr) *refModelWlbDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r refModelWlbDo) Group(cols ...field.Expr) *refModelWlbDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r refModelWlbDo) Having(conds ...gen.Condition) *refModelWlbDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r refModelWlbDo) Limit(limit int) *refModelWlbDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r refModelWlbDo) Offset(offset int) *refModelWlbDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r refModelWlbDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *refModelWlbDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r refModelWlbDo) Unscoped() *refModelWlbDo {
	return r.withDO(r.DO.Unscoped())
}

func (r refModelWlbDo) Create(values ...*entity.RefModelWlb) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r refModelWlbDo) CreateInBatches(values []*entity.RefModelWlb, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r refModelWlbDo) Save(values ...*entity.RefModelWlb) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r refModelWlbDo) First() (*entity.RefModelWlb, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefModelWlb), nil
	}
}

func (r refModelWlbDo) Take() (*entity.RefModelWlb, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefModelWlb), nil
	}
}

func (r refModelWlbDo) Last() (*entity.RefModelWlb, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefModelWlb), nil
	}
}

func (r refModelWlbDo) Find() ([]*entity.RefModelWlb, error) {
	result, err := r.DO.Find()
	return result.([]*entity.RefModelWlb), err
}

func (r refModelWlbDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.RefModelWlb, err error) {
	buf := make([]*entity.RefModelWlb, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r refModelWlbDo) FindInBatches(result *[]*entity.RefModelWlb, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r refModelWlbDo) Attrs(attrs ...field.AssignExpr) *refModelWlbDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r refModelWlbDo) Assign(attrs ...field.AssignExpr) *refModelWlbDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r refModelWlbDo) Joins(fields ...field.RelationField) *refModelWlbDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r refModelWlbDo) Preload(fields ...field.RelationField) *refModelWlbDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r refModelWlbDo) FirstOrInit() (*entity.RefModelWlb, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefModelWlb), nil
	}
}

func (r refModelWlbDo) FirstOrCreate() (*entity.RefModelWlb, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.RefModelWlb), nil
	}
}

func (r refModelWlbDo) FindByPage(offset int, limit int) (result []*entity.RefModelWlb, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r refModelWlbDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r refModelWlbDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r refModelWlbDo) Delete(models ...*entity.RefModelWlb) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *refModelWlbDo) withDO(do gen.Dao) *refModelWlbDo {
	r.DO = *do.(*gen.DO)
	return r
}
