// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package export

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"irwanka/sicerdas/utils/gen-model/entity"
)

func newSkoringMinatSmaV3(db *gorm.DB, opts ...gen.DOOption) skoringMinatSmaV3 {
	_skoringMinatSmaV3 := skoringMinatSmaV3{}

	_skoringMinatSmaV3.skoringMinatSmaV3Do.UseDB(db, opts...)
	_skoringMinatSmaV3.skoringMinatSmaV3Do.UseModel(&entity.SkoringMinatSmaV3{})

	tableName := _skoringMinatSmaV3.skoringMinatSmaV3Do.TableName()
	_skoringMinatSmaV3.ALL = field.NewAsterisk(tableName)
	_skoringMinatSmaV3.ID = field.NewInt32(tableName, "id")
	_skoringMinatSmaV3.IDUser = field.NewInt32(tableName, "id_user")
	_skoringMinatSmaV3.IDQuiz = field.NewInt32(tableName, "id_quiz")
	_skoringMinatSmaV3.TpaIu = field.NewInt32(tableName, "tpa_iu")
	_skoringMinatSmaV3.TpaPv = field.NewInt32(tableName, "tpa_pv")
	_skoringMinatSmaV3.TpaPk = field.NewInt32(tableName, "tpa_pk")
	_skoringMinatSmaV3.TpaPa = field.NewInt32(tableName, "tpa_pa")
	_skoringMinatSmaV3.TpaPs = field.NewInt32(tableName, "tpa_ps")
	_skoringMinatSmaV3.TpaPm = field.NewInt32(tableName, "tpa_pm")
	_skoringMinatSmaV3.TpaKt = field.NewInt32(tableName, "tpa_kt")
	_skoringMinatSmaV3.TpaIq = field.NewInt32(tableName, "tpa_iq")
	_skoringMinatSmaV3.SkorIq = field.NewFloat32(tableName, "skor_iq")
	_skoringMinatSmaV3.MinatSains = field.NewInt32(tableName, "minat_sains")
	_skoringMinatSmaV3.MinatHumaniora = field.NewInt32(tableName, "minat_humaniora")
	_skoringMinatSmaV3.MinatBahasa = field.NewInt32(tableName, "minat_bahasa")
	_skoringMinatSmaV3.MinatRentang = field.NewInt32(tableName, "minat_rentang")
	_skoringMinatSmaV3.SikapAgm = field.NewInt32(tableName, "sikap_agm")
	_skoringMinatSmaV3.SikapPkn = field.NewInt32(tableName, "sikap_pkn")
	_skoringMinatSmaV3.SikapInd = field.NewInt32(tableName, "sikap_ind")
	_skoringMinatSmaV3.SikapEng = field.NewInt32(tableName, "sikap_eng")
	_skoringMinatSmaV3.SikapMat = field.NewInt32(tableName, "sikap_mat")
	_skoringMinatSmaV3.SikapFis = field.NewInt32(tableName, "sikap_fis")
	_skoringMinatSmaV3.SikapBio = field.NewInt32(tableName, "sikap_bio")
	_skoringMinatSmaV3.SikapEko = field.NewInt32(tableName, "sikap_eko")
	_skoringMinatSmaV3.SikapSej = field.NewInt32(tableName, "sikap_sej")
	_skoringMinatSmaV3.SikapGeo = field.NewInt32(tableName, "sikap_geo")
	_skoringMinatSmaV3.SikapIlmuAlam = field.NewInt32(tableName, "sikap_ilmu_alam")
	_skoringMinatSmaV3.SikapIlmuSosial = field.NewInt32(tableName, "sikap_ilmu_sosial")
	_skoringMinatSmaV3.SikapRentang = field.NewInt32(tableName, "sikap_rentang")
	_skoringMinatSmaV3.PribadiMotivasi = field.NewInt32(tableName, "pribadi_motivasi")
	_skoringMinatSmaV3.PribadiJuang = field.NewInt32(tableName, "pribadi_juang")
	_skoringMinatSmaV3.PribadiYakin = field.NewInt32(tableName, "pribadi_yakin")
	_skoringMinatSmaV3.PribadiPercaya = field.NewInt32(tableName, "pribadi_percaya")
	_skoringMinatSmaV3.PribadiKonsep = field.NewInt32(tableName, "pribadi_konsep")
	_skoringMinatSmaV3.PribadiKreativitas = field.NewInt32(tableName, "pribadi_kreativitas")
	_skoringMinatSmaV3.PribadiMimpin = field.NewInt32(tableName, "pribadi_mimpin")
	_skoringMinatSmaV3.PribadiEntrepreneur = field.NewInt32(tableName, "pribadi_entrepreneur")
	_skoringMinatSmaV3.PribadiStress = field.NewInt32(tableName, "pribadi_stress")
	_skoringMinatSmaV3.PribadiEmosi = field.NewInt32(tableName, "pribadi_emosi")
	_skoringMinatSmaV3.PribadiSosial = field.NewInt32(tableName, "pribadi_sosial")
	_skoringMinatSmaV3.PribadiEmpati = field.NewInt32(tableName, "pribadi_empati")
	_skoringMinatSmaV3.RekomMinat = field.NewString(tableName, "rekom_minat")
	_skoringMinatSmaV3.RekomSikapPelajaran = field.NewString(tableName, "rekom_sikap_pelajaran")
	_skoringMinatSmaV3.RekomAkhir = field.NewString(tableName, "rekom_akhir")
	_skoringMinatSmaV3.SelesaiSkoring = field.NewInt32(tableName, "selesai_skoring")
	_skoringMinatSmaV3.MinatIpa1 = field.NewInt16(tableName, "minat_ipa1")
	_skoringMinatSmaV3.MinatIpa2 = field.NewInt16(tableName, "minat_ipa2")
	_skoringMinatSmaV3.MinatIpa3 = field.NewInt16(tableName, "minat_ipa3")
	_skoringMinatSmaV3.MinatIpa4 = field.NewInt16(tableName, "minat_ipa4")
	_skoringMinatSmaV3.MinatIpa5 = field.NewInt16(tableName, "minat_ipa5")
	_skoringMinatSmaV3.MinatIps1 = field.NewInt16(tableName, "minat_ips1")
	_skoringMinatSmaV3.MinatIps2 = field.NewInt16(tableName, "minat_ips2")
	_skoringMinatSmaV3.MinatIps3 = field.NewInt16(tableName, "minat_ips3")
	_skoringMinatSmaV3.MinatIps4 = field.NewInt16(tableName, "minat_ips4")
	_skoringMinatSmaV3.MinatIps5 = field.NewInt16(tableName, "minat_ips5")
	_skoringMinatSmaV3.MinatDinas1 = field.NewString(tableName, "minat_dinas1")
	_skoringMinatSmaV3.MinatDinas2 = field.NewString(tableName, "minat_dinas2")
	_skoringMinatSmaV3.MinatDinas3 = field.NewString(tableName, "minat_dinas3")
	_skoringMinatSmaV3.RekomKelas = field.NewString(tableName, "rekom_kelas")
	_skoringMinatSmaV3.RekomMapelUtama = field.NewString(tableName, "rekom_mapel_utama")
	_skoringMinatSmaV3.RekomMapelTambahan = field.NewString(tableName, "rekom_mapel_tambahan")
	_skoringMinatSmaV3.GayaAuditoris = field.NewInt16(tableName, "gaya_auditoris")
	_skoringMinatSmaV3.GayaVisual = field.NewInt16(tableName, "gaya_visual")
	_skoringMinatSmaV3.GayaKinestetik = field.NewInt16(tableName, "gaya_kinestetik")

	_skoringMinatSmaV3.fillFieldMap()

	return _skoringMinatSmaV3
}

type skoringMinatSmaV3 struct {
	skoringMinatSmaV3Do skoringMinatSmaV3Do

	ALL                 field.Asterisk
	ID                  field.Int32
	IDUser              field.Int32
	IDQuiz              field.Int32
	TpaIu               field.Int32
	TpaPv               field.Int32
	TpaPk               field.Int32
	TpaPa               field.Int32
	TpaPs               field.Int32
	TpaPm               field.Int32
	TpaKt               field.Int32
	TpaIq               field.Int32
	SkorIq              field.Float32
	MinatSains          field.Int32
	MinatHumaniora      field.Int32
	MinatBahasa         field.Int32
	MinatRentang        field.Int32
	SikapAgm            field.Int32
	SikapPkn            field.Int32
	SikapInd            field.Int32
	SikapEng            field.Int32
	SikapMat            field.Int32
	SikapFis            field.Int32
	SikapBio            field.Int32
	SikapEko            field.Int32
	SikapSej            field.Int32
	SikapGeo            field.Int32
	SikapIlmuAlam       field.Int32
	SikapIlmuSosial     field.Int32
	SikapRentang        field.Int32
	PribadiMotivasi     field.Int32
	PribadiJuang        field.Int32
	PribadiYakin        field.Int32
	PribadiPercaya      field.Int32
	PribadiKonsep       field.Int32
	PribadiKreativitas  field.Int32
	PribadiMimpin       field.Int32
	PribadiEntrepreneur field.Int32
	PribadiStress       field.Int32
	PribadiEmosi        field.Int32
	PribadiSosial       field.Int32
	PribadiEmpati       field.Int32
	RekomMinat          field.String
	RekomSikapPelajaran field.String
	RekomAkhir          field.String // REKOM IPA / IPS
	SelesaiSkoring      field.Int32
	MinatIpa1           field.Int16  // Minat Kuliah ILMU ALAM - 1
	MinatIpa2           field.Int16  // Minat Kuliah ILMU ALAM - 2
	MinatIpa3           field.Int16  // Minat Kuliah ILMU ALAM - 3
	MinatIpa4           field.Int16  // Minat Kuliah ULMU ALAM - 4
	MinatIpa5           field.Int16  // Minat Kuliah ILMU ALAM - 5
	MinatIps1           field.Int16  // Minat Kuliah ILMU SOSIAL - 1
	MinatIps2           field.Int16  // Minat Kuliah ILMU SOSIAL - 2
	MinatIps3           field.Int16  // Minat Kuliah ILMU SOSIAL - 3
	MinatIps4           field.Int16  // Minat Kuliah ILMU SOSIAL - 4
	MinatIps5           field.Int16  // Minat Kuliah ILMU SOSIAL -5
	MinatDinas1         field.String // Minat Kuliah DINAS 1
	MinatDinas2         field.String // Miant Kuliah DINAS 2
	MinatDinas3         field.String // Minat Kuliah DINAS 3
	RekomKelas          field.String // REKOM KELOMPOK KELAS
	RekomMapelUtama     field.String // REKOMENDASI MATA PELAJARAN UTAMA
	RekomMapelTambahan  field.String // REKOMENDASI MATA PELAJARAN TAMBAHAN
	GayaAuditoris       field.Int16
	GayaVisual          field.Int16
	GayaKinestetik      field.Int16

	fieldMap map[string]field.Expr
}

func (s skoringMinatSmaV3) Table(newTableName string) *skoringMinatSmaV3 {
	s.skoringMinatSmaV3Do.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s skoringMinatSmaV3) As(alias string) *skoringMinatSmaV3 {
	s.skoringMinatSmaV3Do.DO = *(s.skoringMinatSmaV3Do.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *skoringMinatSmaV3) updateTableName(table string) *skoringMinatSmaV3 {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt32(table, "id")
	s.IDUser = field.NewInt32(table, "id_user")
	s.IDQuiz = field.NewInt32(table, "id_quiz")
	s.TpaIu = field.NewInt32(table, "tpa_iu")
	s.TpaPv = field.NewInt32(table, "tpa_pv")
	s.TpaPk = field.NewInt32(table, "tpa_pk")
	s.TpaPa = field.NewInt32(table, "tpa_pa")
	s.TpaPs = field.NewInt32(table, "tpa_ps")
	s.TpaPm = field.NewInt32(table, "tpa_pm")
	s.TpaKt = field.NewInt32(table, "tpa_kt")
	s.TpaIq = field.NewInt32(table, "tpa_iq")
	s.SkorIq = field.NewFloat32(table, "skor_iq")
	s.MinatSains = field.NewInt32(table, "minat_sains")
	s.MinatHumaniora = field.NewInt32(table, "minat_humaniora")
	s.MinatBahasa = field.NewInt32(table, "minat_bahasa")
	s.MinatRentang = field.NewInt32(table, "minat_rentang")
	s.SikapAgm = field.NewInt32(table, "sikap_agm")
	s.SikapPkn = field.NewInt32(table, "sikap_pkn")
	s.SikapInd = field.NewInt32(table, "sikap_ind")
	s.SikapEng = field.NewInt32(table, "sikap_eng")
	s.SikapMat = field.NewInt32(table, "sikap_mat")
	s.SikapFis = field.NewInt32(table, "sikap_fis")
	s.SikapBio = field.NewInt32(table, "sikap_bio")
	s.SikapEko = field.NewInt32(table, "sikap_eko")
	s.SikapSej = field.NewInt32(table, "sikap_sej")
	s.SikapGeo = field.NewInt32(table, "sikap_geo")
	s.SikapIlmuAlam = field.NewInt32(table, "sikap_ilmu_alam")
	s.SikapIlmuSosial = field.NewInt32(table, "sikap_ilmu_sosial")
	s.SikapRentang = field.NewInt32(table, "sikap_rentang")
	s.PribadiMotivasi = field.NewInt32(table, "pribadi_motivasi")
	s.PribadiJuang = field.NewInt32(table, "pribadi_juang")
	s.PribadiYakin = field.NewInt32(table, "pribadi_yakin")
	s.PribadiPercaya = field.NewInt32(table, "pribadi_percaya")
	s.PribadiKonsep = field.NewInt32(table, "pribadi_konsep")
	s.PribadiKreativitas = field.NewInt32(table, "pribadi_kreativitas")
	s.PribadiMimpin = field.NewInt32(table, "pribadi_mimpin")
	s.PribadiEntrepreneur = field.NewInt32(table, "pribadi_entrepreneur")
	s.PribadiStress = field.NewInt32(table, "pribadi_stress")
	s.PribadiEmosi = field.NewInt32(table, "pribadi_emosi")
	s.PribadiSosial = field.NewInt32(table, "pribadi_sosial")
	s.PribadiEmpati = field.NewInt32(table, "pribadi_empati")
	s.RekomMinat = field.NewString(table, "rekom_minat")
	s.RekomSikapPelajaran = field.NewString(table, "rekom_sikap_pelajaran")
	s.RekomAkhir = field.NewString(table, "rekom_akhir")
	s.SelesaiSkoring = field.NewInt32(table, "selesai_skoring")
	s.MinatIpa1 = field.NewInt16(table, "minat_ipa1")
	s.MinatIpa2 = field.NewInt16(table, "minat_ipa2")
	s.MinatIpa3 = field.NewInt16(table, "minat_ipa3")
	s.MinatIpa4 = field.NewInt16(table, "minat_ipa4")
	s.MinatIpa5 = field.NewInt16(table, "minat_ipa5")
	s.MinatIps1 = field.NewInt16(table, "minat_ips1")
	s.MinatIps2 = field.NewInt16(table, "minat_ips2")
	s.MinatIps3 = field.NewInt16(table, "minat_ips3")
	s.MinatIps4 = field.NewInt16(table, "minat_ips4")
	s.MinatIps5 = field.NewInt16(table, "minat_ips5")
	s.MinatDinas1 = field.NewString(table, "minat_dinas1")
	s.MinatDinas2 = field.NewString(table, "minat_dinas2")
	s.MinatDinas3 = field.NewString(table, "minat_dinas3")
	s.RekomKelas = field.NewString(table, "rekom_kelas")
	s.RekomMapelUtama = field.NewString(table, "rekom_mapel_utama")
	s.RekomMapelTambahan = field.NewString(table, "rekom_mapel_tambahan")
	s.GayaAuditoris = field.NewInt16(table, "gaya_auditoris")
	s.GayaVisual = field.NewInt16(table, "gaya_visual")
	s.GayaKinestetik = field.NewInt16(table, "gaya_kinestetik")

	s.fillFieldMap()

	return s
}

func (s *skoringMinatSmaV3) WithContext(ctx context.Context) *skoringMinatSmaV3Do {
	return s.skoringMinatSmaV3Do.WithContext(ctx)
}

func (s skoringMinatSmaV3) TableName() string { return s.skoringMinatSmaV3Do.TableName() }

func (s skoringMinatSmaV3) Alias() string { return s.skoringMinatSmaV3Do.Alias() }

func (s skoringMinatSmaV3) Columns(cols ...field.Expr) gen.Columns {
	return s.skoringMinatSmaV3Do.Columns(cols...)
}

func (s *skoringMinatSmaV3) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *skoringMinatSmaV3) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 64)
	s.fieldMap["id"] = s.ID
	s.fieldMap["id_user"] = s.IDUser
	s.fieldMap["id_quiz"] = s.IDQuiz
	s.fieldMap["tpa_iu"] = s.TpaIu
	s.fieldMap["tpa_pv"] = s.TpaPv
	s.fieldMap["tpa_pk"] = s.TpaPk
	s.fieldMap["tpa_pa"] = s.TpaPa
	s.fieldMap["tpa_ps"] = s.TpaPs
	s.fieldMap["tpa_pm"] = s.TpaPm
	s.fieldMap["tpa_kt"] = s.TpaKt
	s.fieldMap["tpa_iq"] = s.TpaIq
	s.fieldMap["skor_iq"] = s.SkorIq
	s.fieldMap["minat_sains"] = s.MinatSains
	s.fieldMap["minat_humaniora"] = s.MinatHumaniora
	s.fieldMap["minat_bahasa"] = s.MinatBahasa
	s.fieldMap["minat_rentang"] = s.MinatRentang
	s.fieldMap["sikap_agm"] = s.SikapAgm
	s.fieldMap["sikap_pkn"] = s.SikapPkn
	s.fieldMap["sikap_ind"] = s.SikapInd
	s.fieldMap["sikap_eng"] = s.SikapEng
	s.fieldMap["sikap_mat"] = s.SikapMat
	s.fieldMap["sikap_fis"] = s.SikapFis
	s.fieldMap["sikap_bio"] = s.SikapBio
	s.fieldMap["sikap_eko"] = s.SikapEko
	s.fieldMap["sikap_sej"] = s.SikapSej
	s.fieldMap["sikap_geo"] = s.SikapGeo
	s.fieldMap["sikap_ilmu_alam"] = s.SikapIlmuAlam
	s.fieldMap["sikap_ilmu_sosial"] = s.SikapIlmuSosial
	s.fieldMap["sikap_rentang"] = s.SikapRentang
	s.fieldMap["pribadi_motivasi"] = s.PribadiMotivasi
	s.fieldMap["pribadi_juang"] = s.PribadiJuang
	s.fieldMap["pribadi_yakin"] = s.PribadiYakin
	s.fieldMap["pribadi_percaya"] = s.PribadiPercaya
	s.fieldMap["pribadi_konsep"] = s.PribadiKonsep
	s.fieldMap["pribadi_kreativitas"] = s.PribadiKreativitas
	s.fieldMap["pribadi_mimpin"] = s.PribadiMimpin
	s.fieldMap["pribadi_entrepreneur"] = s.PribadiEntrepreneur
	s.fieldMap["pribadi_stress"] = s.PribadiStress
	s.fieldMap["pribadi_emosi"] = s.PribadiEmosi
	s.fieldMap["pribadi_sosial"] = s.PribadiSosial
	s.fieldMap["pribadi_empati"] = s.PribadiEmpati
	s.fieldMap["rekom_minat"] = s.RekomMinat
	s.fieldMap["rekom_sikap_pelajaran"] = s.RekomSikapPelajaran
	s.fieldMap["rekom_akhir"] = s.RekomAkhir
	s.fieldMap["selesai_skoring"] = s.SelesaiSkoring
	s.fieldMap["minat_ipa1"] = s.MinatIpa1
	s.fieldMap["minat_ipa2"] = s.MinatIpa2
	s.fieldMap["minat_ipa3"] = s.MinatIpa3
	s.fieldMap["minat_ipa4"] = s.MinatIpa4
	s.fieldMap["minat_ipa5"] = s.MinatIpa5
	s.fieldMap["minat_ips1"] = s.MinatIps1
	s.fieldMap["minat_ips2"] = s.MinatIps2
	s.fieldMap["minat_ips3"] = s.MinatIps3
	s.fieldMap["minat_ips4"] = s.MinatIps4
	s.fieldMap["minat_ips5"] = s.MinatIps5
	s.fieldMap["minat_dinas1"] = s.MinatDinas1
	s.fieldMap["minat_dinas2"] = s.MinatDinas2
	s.fieldMap["minat_dinas3"] = s.MinatDinas3
	s.fieldMap["rekom_kelas"] = s.RekomKelas
	s.fieldMap["rekom_mapel_utama"] = s.RekomMapelUtama
	s.fieldMap["rekom_mapel_tambahan"] = s.RekomMapelTambahan
	s.fieldMap["gaya_auditoris"] = s.GayaAuditoris
	s.fieldMap["gaya_visual"] = s.GayaVisual
	s.fieldMap["gaya_kinestetik"] = s.GayaKinestetik
}

func (s skoringMinatSmaV3) clone(db *gorm.DB) skoringMinatSmaV3 {
	s.skoringMinatSmaV3Do.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s skoringMinatSmaV3) replaceDB(db *gorm.DB) skoringMinatSmaV3 {
	s.skoringMinatSmaV3Do.ReplaceDB(db)
	return s
}

type skoringMinatSmaV3Do struct{ gen.DO }

func (s skoringMinatSmaV3Do) Debug() *skoringMinatSmaV3Do {
	return s.withDO(s.DO.Debug())
}

func (s skoringMinatSmaV3Do) WithContext(ctx context.Context) *skoringMinatSmaV3Do {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s skoringMinatSmaV3Do) ReadDB() *skoringMinatSmaV3Do {
	return s.Clauses(dbresolver.Read)
}

func (s skoringMinatSmaV3Do) WriteDB() *skoringMinatSmaV3Do {
	return s.Clauses(dbresolver.Write)
}

func (s skoringMinatSmaV3Do) Session(config *gorm.Session) *skoringMinatSmaV3Do {
	return s.withDO(s.DO.Session(config))
}

func (s skoringMinatSmaV3Do) Clauses(conds ...clause.Expression) *skoringMinatSmaV3Do {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s skoringMinatSmaV3Do) Returning(value interface{}, columns ...string) *skoringMinatSmaV3Do {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s skoringMinatSmaV3Do) Not(conds ...gen.Condition) *skoringMinatSmaV3Do {
	return s.withDO(s.DO.Not(conds...))
}

func (s skoringMinatSmaV3Do) Or(conds ...gen.Condition) *skoringMinatSmaV3Do {
	return s.withDO(s.DO.Or(conds...))
}

func (s skoringMinatSmaV3Do) Select(conds ...field.Expr) *skoringMinatSmaV3Do {
	return s.withDO(s.DO.Select(conds...))
}

func (s skoringMinatSmaV3Do) Where(conds ...gen.Condition) *skoringMinatSmaV3Do {
	return s.withDO(s.DO.Where(conds...))
}

func (s skoringMinatSmaV3Do) Order(conds ...field.Expr) *skoringMinatSmaV3Do {
	return s.withDO(s.DO.Order(conds...))
}

func (s skoringMinatSmaV3Do) Distinct(cols ...field.Expr) *skoringMinatSmaV3Do {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s skoringMinatSmaV3Do) Omit(cols ...field.Expr) *skoringMinatSmaV3Do {
	return s.withDO(s.DO.Omit(cols...))
}

func (s skoringMinatSmaV3Do) Join(table schema.Tabler, on ...field.Expr) *skoringMinatSmaV3Do {
	return s.withDO(s.DO.Join(table, on...))
}

func (s skoringMinatSmaV3Do) LeftJoin(table schema.Tabler, on ...field.Expr) *skoringMinatSmaV3Do {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s skoringMinatSmaV3Do) RightJoin(table schema.Tabler, on ...field.Expr) *skoringMinatSmaV3Do {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s skoringMinatSmaV3Do) Group(cols ...field.Expr) *skoringMinatSmaV3Do {
	return s.withDO(s.DO.Group(cols...))
}

func (s skoringMinatSmaV3Do) Having(conds ...gen.Condition) *skoringMinatSmaV3Do {
	return s.withDO(s.DO.Having(conds...))
}

func (s skoringMinatSmaV3Do) Limit(limit int) *skoringMinatSmaV3Do {
	return s.withDO(s.DO.Limit(limit))
}

func (s skoringMinatSmaV3Do) Offset(offset int) *skoringMinatSmaV3Do {
	return s.withDO(s.DO.Offset(offset))
}

func (s skoringMinatSmaV3Do) Scopes(funcs ...func(gen.Dao) gen.Dao) *skoringMinatSmaV3Do {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s skoringMinatSmaV3Do) Unscoped() *skoringMinatSmaV3Do {
	return s.withDO(s.DO.Unscoped())
}

func (s skoringMinatSmaV3Do) Create(values ...*entity.SkoringMinatSmaV3) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s skoringMinatSmaV3Do) CreateInBatches(values []*entity.SkoringMinatSmaV3, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s skoringMinatSmaV3Do) Save(values ...*entity.SkoringMinatSmaV3) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s skoringMinatSmaV3Do) First() (*entity.SkoringMinatSmaV3, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SkoringMinatSmaV3), nil
	}
}

func (s skoringMinatSmaV3Do) Take() (*entity.SkoringMinatSmaV3, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SkoringMinatSmaV3), nil
	}
}

func (s skoringMinatSmaV3Do) Last() (*entity.SkoringMinatSmaV3, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SkoringMinatSmaV3), nil
	}
}

func (s skoringMinatSmaV3Do) Find() ([]*entity.SkoringMinatSmaV3, error) {
	result, err := s.DO.Find()
	return result.([]*entity.SkoringMinatSmaV3), err
}

func (s skoringMinatSmaV3Do) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.SkoringMinatSmaV3, err error) {
	buf := make([]*entity.SkoringMinatSmaV3, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s skoringMinatSmaV3Do) FindInBatches(result *[]*entity.SkoringMinatSmaV3, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s skoringMinatSmaV3Do) Attrs(attrs ...field.AssignExpr) *skoringMinatSmaV3Do {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s skoringMinatSmaV3Do) Assign(attrs ...field.AssignExpr) *skoringMinatSmaV3Do {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s skoringMinatSmaV3Do) Joins(fields ...field.RelationField) *skoringMinatSmaV3Do {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s skoringMinatSmaV3Do) Preload(fields ...field.RelationField) *skoringMinatSmaV3Do {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s skoringMinatSmaV3Do) FirstOrInit() (*entity.SkoringMinatSmaV3, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SkoringMinatSmaV3), nil
	}
}

func (s skoringMinatSmaV3Do) FirstOrCreate() (*entity.SkoringMinatSmaV3, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SkoringMinatSmaV3), nil
	}
}

func (s skoringMinatSmaV3Do) FindByPage(offset int, limit int) (result []*entity.SkoringMinatSmaV3, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s skoringMinatSmaV3Do) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s skoringMinatSmaV3Do) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s skoringMinatSmaV3Do) Delete(models ...*entity.SkoringMinatSmaV3) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *skoringMinatSmaV3Do) withDO(do gen.Dao) *skoringMinatSmaV3Do {
	s.DO = *do.(*gen.DO)
	return s
}
