// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package export

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"irwanka/sicerdas/utils/gen-model/entity"
)

func newSkorKuliahDina(db *gorm.DB, opts ...gen.DOOption) skorKuliahDina {
	_skorKuliahDina := skorKuliahDina{}

	_skorKuliahDina.skorKuliahDinaDo.UseDB(db, opts...)
	_skorKuliahDina.skorKuliahDinaDo.UseModel(&entity.SkorKuliahDina{})

	tableName := _skorKuliahDina.skorKuliahDinaDo.TableName()
	_skorKuliahDina.ALL = field.NewAsterisk(tableName)
	_skorKuliahDina.IDUser = field.NewInt32(tableName, "id_user")
	_skorKuliahDina.IDQuiz = field.NewInt32(tableName, "id_quiz")
	_skorKuliahDina.MinatDinas1 = field.NewString(tableName, "minat_dinas1")
	_skorKuliahDina.MinatDinas2 = field.NewString(tableName, "minat_dinas2")
	_skorKuliahDina.MinatDinas3 = field.NewString(tableName, "minat_dinas3")

	_skorKuliahDina.fillFieldMap()

	return _skorKuliahDina
}

type skorKuliahDina struct {
	skorKuliahDinaDo skorKuliahDinaDo

	ALL         field.Asterisk
	IDUser      field.Int32
	IDQuiz      field.Int32
	MinatDinas1 field.String
	MinatDinas2 field.String
	MinatDinas3 field.String

	fieldMap map[string]field.Expr
}

func (s skorKuliahDina) Table(newTableName string) *skorKuliahDina {
	s.skorKuliahDinaDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s skorKuliahDina) As(alias string) *skorKuliahDina {
	s.skorKuliahDinaDo.DO = *(s.skorKuliahDinaDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *skorKuliahDina) updateTableName(table string) *skorKuliahDina {
	s.ALL = field.NewAsterisk(table)
	s.IDUser = field.NewInt32(table, "id_user")
	s.IDQuiz = field.NewInt32(table, "id_quiz")
	s.MinatDinas1 = field.NewString(table, "minat_dinas1")
	s.MinatDinas2 = field.NewString(table, "minat_dinas2")
	s.MinatDinas3 = field.NewString(table, "minat_dinas3")

	s.fillFieldMap()

	return s
}

func (s *skorKuliahDina) WithContext(ctx context.Context) *skorKuliahDinaDo {
	return s.skorKuliahDinaDo.WithContext(ctx)
}

func (s skorKuliahDina) TableName() string { return s.skorKuliahDinaDo.TableName() }

func (s skorKuliahDina) Alias() string { return s.skorKuliahDinaDo.Alias() }

func (s skorKuliahDina) Columns(cols ...field.Expr) gen.Columns {
	return s.skorKuliahDinaDo.Columns(cols...)
}

func (s *skorKuliahDina) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *skorKuliahDina) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 5)
	s.fieldMap["id_user"] = s.IDUser
	s.fieldMap["id_quiz"] = s.IDQuiz
	s.fieldMap["minat_dinas1"] = s.MinatDinas1
	s.fieldMap["minat_dinas2"] = s.MinatDinas2
	s.fieldMap["minat_dinas3"] = s.MinatDinas3
}

func (s skorKuliahDina) clone(db *gorm.DB) skorKuliahDina {
	s.skorKuliahDinaDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s skorKuliahDina) replaceDB(db *gorm.DB) skorKuliahDina {
	s.skorKuliahDinaDo.ReplaceDB(db)
	return s
}

type skorKuliahDinaDo struct{ gen.DO }

func (s skorKuliahDinaDo) Debug() *skorKuliahDinaDo {
	return s.withDO(s.DO.Debug())
}

func (s skorKuliahDinaDo) WithContext(ctx context.Context) *skorKuliahDinaDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s skorKuliahDinaDo) ReadDB() *skorKuliahDinaDo {
	return s.Clauses(dbresolver.Read)
}

func (s skorKuliahDinaDo) WriteDB() *skorKuliahDinaDo {
	return s.Clauses(dbresolver.Write)
}

func (s skorKuliahDinaDo) Session(config *gorm.Session) *skorKuliahDinaDo {
	return s.withDO(s.DO.Session(config))
}

func (s skorKuliahDinaDo) Clauses(conds ...clause.Expression) *skorKuliahDinaDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s skorKuliahDinaDo) Returning(value interface{}, columns ...string) *skorKuliahDinaDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s skorKuliahDinaDo) Not(conds ...gen.Condition) *skorKuliahDinaDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s skorKuliahDinaDo) Or(conds ...gen.Condition) *skorKuliahDinaDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s skorKuliahDinaDo) Select(conds ...field.Expr) *skorKuliahDinaDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s skorKuliahDinaDo) Where(conds ...gen.Condition) *skorKuliahDinaDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s skorKuliahDinaDo) Order(conds ...field.Expr) *skorKuliahDinaDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s skorKuliahDinaDo) Distinct(cols ...field.Expr) *skorKuliahDinaDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s skorKuliahDinaDo) Omit(cols ...field.Expr) *skorKuliahDinaDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s skorKuliahDinaDo) Join(table schema.Tabler, on ...field.Expr) *skorKuliahDinaDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s skorKuliahDinaDo) LeftJoin(table schema.Tabler, on ...field.Expr) *skorKuliahDinaDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s skorKuliahDinaDo) RightJoin(table schema.Tabler, on ...field.Expr) *skorKuliahDinaDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s skorKuliahDinaDo) Group(cols ...field.Expr) *skorKuliahDinaDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s skorKuliahDinaDo) Having(conds ...gen.Condition) *skorKuliahDinaDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s skorKuliahDinaDo) Limit(limit int) *skorKuliahDinaDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s skorKuliahDinaDo) Offset(offset int) *skorKuliahDinaDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s skorKuliahDinaDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *skorKuliahDinaDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s skorKuliahDinaDo) Unscoped() *skorKuliahDinaDo {
	return s.withDO(s.DO.Unscoped())
}

func (s skorKuliahDinaDo) Create(values ...*entity.SkorKuliahDina) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s skorKuliahDinaDo) CreateInBatches(values []*entity.SkorKuliahDina, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s skorKuliahDinaDo) Save(values ...*entity.SkorKuliahDina) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s skorKuliahDinaDo) First() (*entity.SkorKuliahDina, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SkorKuliahDina), nil
	}
}

func (s skorKuliahDinaDo) Take() (*entity.SkorKuliahDina, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SkorKuliahDina), nil
	}
}

func (s skorKuliahDinaDo) Last() (*entity.SkorKuliahDina, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SkorKuliahDina), nil
	}
}

func (s skorKuliahDinaDo) Find() ([]*entity.SkorKuliahDina, error) {
	result, err := s.DO.Find()
	return result.([]*entity.SkorKuliahDina), err
}

func (s skorKuliahDinaDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.SkorKuliahDina, err error) {
	buf := make([]*entity.SkorKuliahDina, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s skorKuliahDinaDo) FindInBatches(result *[]*entity.SkorKuliahDina, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s skorKuliahDinaDo) Attrs(attrs ...field.AssignExpr) *skorKuliahDinaDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s skorKuliahDinaDo) Assign(attrs ...field.AssignExpr) *skorKuliahDinaDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s skorKuliahDinaDo) Joins(fields ...field.RelationField) *skorKuliahDinaDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s skorKuliahDinaDo) Preload(fields ...field.RelationField) *skorKuliahDinaDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s skorKuliahDinaDo) FirstOrInit() (*entity.SkorKuliahDina, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SkorKuliahDina), nil
	}
}

func (s skorKuliahDinaDo) FirstOrCreate() (*entity.SkorKuliahDina, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SkorKuliahDina), nil
	}
}

func (s skorKuliahDinaDo) FindByPage(offset int, limit int) (result []*entity.SkorKuliahDina, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s skorKuliahDinaDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s skorKuliahDinaDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s skorKuliahDinaDo) Delete(models ...*entity.SkorKuliahDina) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *skorKuliahDinaDo) withDO(do gen.Dao) *skorKuliahDinaDo {
	s.DO = *do.(*gen.DO)
	return s
}
