// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package export

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"irwanka/sicerdas/utils/gen-model/entity"
)

func newSoalTipologiJung(db *gorm.DB, opts ...gen.DOOption) soalTipologiJung {
	_soalTipologiJung := soalTipologiJung{}

	_soalTipologiJung.soalTipologiJungDo.UseDB(db, opts...)
	_soalTipologiJung.soalTipologiJungDo.UseModel(&entity.SoalTipologiJung{})

	tableName := _soalTipologiJung.soalTipologiJungDo.TableName()
	_soalTipologiJung.ALL = field.NewAsterisk(tableName)
	_soalTipologiJung.IDSoal = field.NewInt32(tableName, "id_soal")
	_soalTipologiJung.Kolom = field.NewString(tableName, "kolom")
	_soalTipologiJung.Urutan = field.NewInt32(tableName, "urutan")
	_soalTipologiJung.Pernyataan = field.NewString(tableName, "pernyataan")
	_soalTipologiJung.PilihanA = field.NewString(tableName, "pilihan_a")
	_soalTipologiJung.PilihanB = field.NewString(tableName, "pilihan_b")
	_soalTipologiJung.UUID = field.NewString(tableName, "uuid")

	_soalTipologiJung.fillFieldMap()

	return _soalTipologiJung
}

type soalTipologiJung struct {
	soalTipologiJungDo soalTipologiJungDo

	ALL        field.Asterisk
	IDSoal     field.Int32
	Kolom      field.String
	Urutan     field.Int32
	Pernyataan field.String
	PilihanA   field.String
	PilihanB   field.String
	UUID       field.String

	fieldMap map[string]field.Expr
}

func (s soalTipologiJung) Table(newTableName string) *soalTipologiJung {
	s.soalTipologiJungDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s soalTipologiJung) As(alias string) *soalTipologiJung {
	s.soalTipologiJungDo.DO = *(s.soalTipologiJungDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *soalTipologiJung) updateTableName(table string) *soalTipologiJung {
	s.ALL = field.NewAsterisk(table)
	s.IDSoal = field.NewInt32(table, "id_soal")
	s.Kolom = field.NewString(table, "kolom")
	s.Urutan = field.NewInt32(table, "urutan")
	s.Pernyataan = field.NewString(table, "pernyataan")
	s.PilihanA = field.NewString(table, "pilihan_a")
	s.PilihanB = field.NewString(table, "pilihan_b")
	s.UUID = field.NewString(table, "uuid")

	s.fillFieldMap()

	return s
}

func (s *soalTipologiJung) WithContext(ctx context.Context) *soalTipologiJungDo {
	return s.soalTipologiJungDo.WithContext(ctx)
}

func (s soalTipologiJung) TableName() string { return s.soalTipologiJungDo.TableName() }

func (s soalTipologiJung) Alias() string { return s.soalTipologiJungDo.Alias() }

func (s soalTipologiJung) Columns(cols ...field.Expr) gen.Columns {
	return s.soalTipologiJungDo.Columns(cols...)
}

func (s *soalTipologiJung) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *soalTipologiJung) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 7)
	s.fieldMap["id_soal"] = s.IDSoal
	s.fieldMap["kolom"] = s.Kolom
	s.fieldMap["urutan"] = s.Urutan
	s.fieldMap["pernyataan"] = s.Pernyataan
	s.fieldMap["pilihan_a"] = s.PilihanA
	s.fieldMap["pilihan_b"] = s.PilihanB
	s.fieldMap["uuid"] = s.UUID
}

func (s soalTipologiJung) clone(db *gorm.DB) soalTipologiJung {
	s.soalTipologiJungDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s soalTipologiJung) replaceDB(db *gorm.DB) soalTipologiJung {
	s.soalTipologiJungDo.ReplaceDB(db)
	return s
}

type soalTipologiJungDo struct{ gen.DO }

func (s soalTipologiJungDo) Debug() *soalTipologiJungDo {
	return s.withDO(s.DO.Debug())
}

func (s soalTipologiJungDo) WithContext(ctx context.Context) *soalTipologiJungDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s soalTipologiJungDo) ReadDB() *soalTipologiJungDo {
	return s.Clauses(dbresolver.Read)
}

func (s soalTipologiJungDo) WriteDB() *soalTipologiJungDo {
	return s.Clauses(dbresolver.Write)
}

func (s soalTipologiJungDo) Session(config *gorm.Session) *soalTipologiJungDo {
	return s.withDO(s.DO.Session(config))
}

func (s soalTipologiJungDo) Clauses(conds ...clause.Expression) *soalTipologiJungDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s soalTipologiJungDo) Returning(value interface{}, columns ...string) *soalTipologiJungDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s soalTipologiJungDo) Not(conds ...gen.Condition) *soalTipologiJungDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s soalTipologiJungDo) Or(conds ...gen.Condition) *soalTipologiJungDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s soalTipologiJungDo) Select(conds ...field.Expr) *soalTipologiJungDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s soalTipologiJungDo) Where(conds ...gen.Condition) *soalTipologiJungDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s soalTipologiJungDo) Order(conds ...field.Expr) *soalTipologiJungDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s soalTipologiJungDo) Distinct(cols ...field.Expr) *soalTipologiJungDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s soalTipologiJungDo) Omit(cols ...field.Expr) *soalTipologiJungDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s soalTipologiJungDo) Join(table schema.Tabler, on ...field.Expr) *soalTipologiJungDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s soalTipologiJungDo) LeftJoin(table schema.Tabler, on ...field.Expr) *soalTipologiJungDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s soalTipologiJungDo) RightJoin(table schema.Tabler, on ...field.Expr) *soalTipologiJungDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s soalTipologiJungDo) Group(cols ...field.Expr) *soalTipologiJungDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s soalTipologiJungDo) Having(conds ...gen.Condition) *soalTipologiJungDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s soalTipologiJungDo) Limit(limit int) *soalTipologiJungDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s soalTipologiJungDo) Offset(offset int) *soalTipologiJungDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s soalTipologiJungDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *soalTipologiJungDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s soalTipologiJungDo) Unscoped() *soalTipologiJungDo {
	return s.withDO(s.DO.Unscoped())
}

func (s soalTipologiJungDo) Create(values ...*entity.SoalTipologiJung) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s soalTipologiJungDo) CreateInBatches(values []*entity.SoalTipologiJung, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s soalTipologiJungDo) Save(values ...*entity.SoalTipologiJung) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s soalTipologiJungDo) First() (*entity.SoalTipologiJung, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SoalTipologiJung), nil
	}
}

func (s soalTipologiJungDo) Take() (*entity.SoalTipologiJung, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SoalTipologiJung), nil
	}
}

func (s soalTipologiJungDo) Last() (*entity.SoalTipologiJung, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SoalTipologiJung), nil
	}
}

func (s soalTipologiJungDo) Find() ([]*entity.SoalTipologiJung, error) {
	result, err := s.DO.Find()
	return result.([]*entity.SoalTipologiJung), err
}

func (s soalTipologiJungDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.SoalTipologiJung, err error) {
	buf := make([]*entity.SoalTipologiJung, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s soalTipologiJungDo) FindInBatches(result *[]*entity.SoalTipologiJung, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s soalTipologiJungDo) Attrs(attrs ...field.AssignExpr) *soalTipologiJungDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s soalTipologiJungDo) Assign(attrs ...field.AssignExpr) *soalTipologiJungDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s soalTipologiJungDo) Joins(fields ...field.RelationField) *soalTipologiJungDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s soalTipologiJungDo) Preload(fields ...field.RelationField) *soalTipologiJungDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s soalTipologiJungDo) FirstOrInit() (*entity.SoalTipologiJung, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SoalTipologiJung), nil
	}
}

func (s soalTipologiJungDo) FirstOrCreate() (*entity.SoalTipologiJung, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.SoalTipologiJung), nil
	}
}

func (s soalTipologiJungDo) FindByPage(offset int, limit int) (result []*entity.SoalTipologiJung, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s soalTipologiJungDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s soalTipologiJungDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s soalTipologiJungDo) Delete(models ...*entity.SoalTipologiJung) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *soalTipologiJungDo) withDO(do gen.Dao) *soalTipologiJungDo {
	s.DO = *do.(*gen.DO)
	return s
}
